import type { Plan, PortfolioItem, Testimonial, BlogPost, FAQItem, DiagnosticQuestion, OnboardingStep, Resource, BeforeAfterExample, ProfileQuestion } from './types'

export const config = {
  SITE_URL: 'https://mindzy.me',
  CONTACT_EMAIL: 'contact@mindzy.me',
  CALENDLY_URL: 'https://calendly.com/mindzy/consultation',
  CONTRACT_URL: '/contract',
  WHATSAPP_PHONE_NUMBER: '+41XXXXXXXXX',
  WHATSAPP_PHONE_ID: 'XXXXXXXXXX',
  WHATSAPP_BUSINESS_ID: 'XXXXXXXXXX',
  WHATSAPP_API_VERSION: 'v18.0',
  WHATSAPP_LINK: 'https://wa.me/41XXXXXXXXX',
  LINKEDIN_URL: 'https://linkedin.com/company/mindzy',
}

export const plans: Plan[] = [
  { id: 'basic', price: 49, setup: 300, pages: 1, articles: 0, booking: false, payments: false, products: 0, gmb: true },
  { id: 'pro', price: 99, setup: 300, pages: 5, articles: 15, booking: true, payments: false, products: 0, gmb: true },
  { id: 'business', price: 129, setup: 500, pages: 5, articles: 15, booking: true, payments: true, products: 0, gmb: true },
  { id: 'ecommerce', price: 149, setup: 500, pages: 5, articles: 0, booking: false, payments: true, products: 20, gmb: true },
]

export const professions = ['consultant', 'freelance', 'therapeute', 'coach', 'boutique', 'restaurant', 'psychologue', 'coach-sportif', 'artisan'] as const

export const portfolioItems: PortfolioItem[] = [
  ...Array.from({ length: 40 }, (_, i) => ({
    id: `portfolio-${i + 1}`,
    title: {
      fr: ['Agence Créative', 'Restaurant Le Gourmet', 'Cabinet Conseil', 'Studio Photo', 'Boutique Mode', 'Coach Business', 'Artisan Menuisier', 'Salon de Coiffure', 'Architecte d\'Intérieur', 'Avocat & Associés'][i % 10] + ` ${Math.floor(i / 10) + 1}`,
      en: ['Creative Agency', 'Le Gourmet Restaurant', 'Consulting Firm', 'Photo Studio', 'Fashion Boutique', 'Business Coach', 'Carpenter Craft', 'Hair Salon', 'Interior Architect', 'Law Firm'][i % 10] + ` ${Math.floor(i / 10) + 1}`,
      es: ['Agencia Creativa', 'Restaurante Gourmet', 'Consultora', 'Estudio Fotográfico', 'Boutique Moda', 'Coach Empresarial', 'Artesano Carpintero', 'Salón de Belleza', 'Arquitecto Interior', 'Bufete de Abogados'][i % 10] + ` ${Math.floor(i / 10) + 1}`
    },
    description: { fr: 'Site web professionnel avec réservation en ligne et SEO optimisé.', en: 'Professional website with online booking and optimized SEO.', es: 'Sitio web profesional con reservas en línea y SEO optimizado.' },
    category: (['therapist', 'clinic', 'coach', 'ecom'] as const)[i % 4],
    profession: professions[i % 6],
    image: `/images/portfolio/placeholder-${(i % 6) + 1}.jpg`,
    featured: i < 6,
  })),
  { id: 'portfolio-t1', title: { fr: 'Cabinet de Sophrologie Harmony', en: 'Harmony Sophrology Practice', es: 'Consulta de Sofrología Harmony' }, description: { fr: 'Site vitrine avec prise de rendez-vous en ligne et présentation des séances.', en: 'Showcase website with online booking and session presentation.', es: 'Sitio web con reservas en línea y presentación de sesiones.' }, category: 'therapist' as const, profession: 'therapeute' as typeof professions[number], image: '/images/portfolio/placeholder-1.jpg' },
  { id: 'portfolio-t2', title: { fr: 'Thérapeute Holistique Lumière', en: 'Lumière Holistic Therapist', es: 'Terapeuta Holístico Lumière' }, description: { fr: 'Site professionnel avec blog bien-être et réservation de consultations.', en: 'Professional website with wellness blog and consultation booking.', es: 'Sitio profesional con blog de bienestar y reserva de consultas.' }, category: 'therapist' as const, profession: 'therapeute' as typeof professions[number], image: '/images/portfolio/placeholder-2.jpg' },
  { id: 'portfolio-t3', title: { fr: 'Centre de Thérapie Zen', en: 'Zen Therapy Center', es: 'Centro de Terapia Zen' }, description: { fr: 'Site multi-praticiens avec agenda partagé et fiches spécialités.', en: 'Multi-practitioner site with shared calendar and specialty pages.', es: 'Sitio multi-profesional con agenda compartida y fichas de especialidades.' }, category: 'therapist' as const, profession: 'therapeute' as typeof professions[number], image: '/images/portfolio/placeholder-3.jpg' },
  { id: 'portfolio-p1', title: { fr: 'Cabinet de Psychologie Sérénité', en: 'Serenity Psychology Practice', es: 'Consulta de Psicología Serenidad' }, description: { fr: 'Site professionnel avec formulaire de premier contact et présentation des approches thérapeutiques.', en: 'Professional website with first contact form and therapeutic approach presentation.', es: 'Sitio profesional con formulario de contacto y presentación de enfoques terapéuticos.' }, category: 'therapist' as const, profession: 'psychologue' as typeof professions[number], image: '/images/portfolio/placeholder-4.jpg' },
  { id: 'portfolio-p2', title: { fr: 'Psychologue Marie Laurent', en: 'Psychologist Marie Laurent', es: 'Psicóloga Marie Laurent' }, description: { fr: 'Site vitrine élégant avec prise de rendez-vous en ligne et blog psycho.', en: 'Elegant showcase site with online booking and psychology blog.', es: 'Sitio elegante con reservas en línea y blog de psicología.' }, category: 'therapist' as const, profession: 'psychologue' as typeof professions[number], image: '/images/portfolio/placeholder-5.jpg' },
  { id: 'portfolio-p3', title: { fr: 'Centre de Psychothérapie Éveil', en: 'Éveil Psychotherapy Center', es: 'Centro de Psicoterapia Éveil' }, description: { fr: 'Site de groupe avec profils individuels, spécialités et prise de RDV.', en: 'Group practice site with individual profiles, specialties and booking.', es: 'Sitio de grupo con perfiles individuales, especialidades y reservas.' }, category: 'clinic' as const, profession: 'psychologue' as typeof professions[number], image: '/images/portfolio/placeholder-6.jpg' },
  { id: 'portfolio-cs1', title: { fr: 'Coach Sportif FitPro', en: 'FitPro Sports Coach', es: 'Coach Deportivo FitPro' }, description: { fr: 'Site dynamique avec programmes d\'entraînement, réservation de séances et témoignages clients.', en: 'Dynamic site with training programs, session booking and client testimonials.', es: 'Sitio dinámico con programas de entrenamiento, reserva de sesiones y testimonios.' }, category: 'coach' as const, profession: 'coach-sportif' as typeof professions[number], image: '/images/portfolio/placeholder-1.jpg' },
  { id: 'portfolio-cs2', title: { fr: 'Studio de Personal Training Énergie', en: 'Énergie Personal Training Studio', es: 'Estudio de Entrenamiento Personal Énergie' }, description: { fr: 'Site avec plans tarifaires, galerie avant/après et paiement en ligne.', en: 'Site with pricing plans, before/after gallery and online payment.', es: 'Sitio con planes de precios, galería antes/después y pago en línea.' }, category: 'coach' as const, profession: 'coach-sportif' as typeof professions[number], image: '/images/portfolio/placeholder-2.jpg' },
  { id: 'portfolio-cs3', title: { fr: 'Coach Sportif Outdoor Maxime', en: 'Outdoor Sports Coach Maxime', es: 'Coach Deportivo Outdoor Maxime' }, description: { fr: 'Site avec calendrier de cours collectifs, inscription en ligne et blog fitness.', en: 'Site with group class calendar, online registration and fitness blog.', es: 'Sitio con calendario de clases grupales, inscripción en línea y blog fitness.' }, category: 'coach' as const, profession: 'coach-sportif' as typeof professions[number], image: '/images/portfolio/placeholder-3.jpg' },
]

export const testimonials: Testimonial[] = [
  { id: 't1', name: 'Marie Dupont', profession: { fr: 'Consultante Marketing', en: 'Marketing Consultant', es: 'Consultora de Marketing' }, quote: { fr: 'Mindzy a transformé ma visibilité en ligne. Je reçois 3x plus de demandes clients.', en: 'Mindzy transformed my online visibility. I receive 3x more client requests.', es: 'Mindzy transformó mi visibilidad. Recibo 3 veces más solicitudes de clientes.' }, rating: 5 },
  { id: 't2', name: 'Jean-Pierre Martin', profession: { fr: 'Restaurateur', en: 'Restaurant Owner', es: 'Restaurador' }, quote: { fr: 'Le système de réservation a révolutionné mon restaurant. Fini les appels sans fin !', en: 'The booking system revolutionized my restaurant. No more endless phone calls!', es: 'El sistema de reservas revolucionó mi restaurante. ¡Se acabaron las llamadas interminables!' }, rating: 5 },
  { id: 't3', name: 'Sophie Bernard', profession: { fr: 'Coach Business', en: 'Business Coach', es: 'Coach Empresarial' }, quote: { fr: 'Un accompagnement professionnel de A à Z. Mon site génère maintenant des clients automatiquement.', en: 'Professional support from A to Z. My site now generates clients automatically.', es: 'Apoyo profesional de principio a fin. Mi sitio genera clientes automáticamente.' }, rating: 5 },
  { id: 't4', name: 'Lucas Petit', profession: { fr: 'Photographe', en: 'Photographer', es: 'Fotógrafo' }, quote: { fr: 'Mon portfolio en ligne attire des clients que je n\'aurais jamais atteint autrement.', en: 'My online portfolio attracts clients I would never have reached otherwise.', es: 'Mi portafolio en línea atrae clientes que nunca habría alcanzado de otra manera.' }, rating: 5 },
  { id: 't5', name: 'Émilie Roux', profession: { fr: 'Avocate', en: 'Lawyer', es: 'Abogada' }, quote: { fr: 'Un site professionnel qui reflète parfaitement l\'image de mon cabinet.', en: 'A professional site that perfectly reflects my firm\'s image.', es: 'Un sitio profesional que refleja perfectamente la imagen de mi despacho.' }, rating: 5 },
  { id: 't6', name: 'Thomas Moreau', profession: { fr: 'Artisan Menuisier', en: 'Carpenter Craftsman', es: 'Artesano Carpintero' }, quote: { fr: 'Grâce à Mindzy, j\'ai maintenant une vitrine en ligne digne de mon savoir-faire.', en: 'Thanks to Mindzy, I now have an online showcase worthy of my craftsmanship.', es: 'Gracias a Mindzy, ahora tengo un escaparate en línea digno de mi artesanía.' }, rating: 5 },
]

export const blogPosts: BlogPost[] = [
  { slug: 'pourquoi-site-web-professionnel', title: { fr: 'Pourquoi chaque entrepreneur a besoin d\'un site en 2025', en: 'Why every entrepreneur needs a website in 2025', es: 'Por qué cada emprendedor necesita un sitio en 2025' }, excerpt: { fr: 'Découvrez pourquoi une présence en ligne est indispensable pour votre activité.', en: 'Discover why an online presence is essential for your business.', es: 'Descubra por qué una presencia en línea es esencial para su negocio.' }, category: 'marketing', author: 'Mindzy', date: '2025-01-15', image: '/images/blog/1.jpg', readingTime: 5 },
  { slug: 'seo-entrepreneurs-guide', title: { fr: 'SEO pour entrepreneurs : le guide complet', en: 'SEO for entrepreneurs: the complete guide', es: 'SEO para emprendedores: la guía completa' }, excerpt: { fr: 'Apprenez à optimiser votre site pour Google et attirer plus de clients.', en: 'Learn to optimize your site for Google and attract more clients.', es: 'Aprenda a optimizar su sitio para Google y atraer más clientes.' }, category: 'seo', author: 'Mindzy', date: '2025-01-10', image: '/images/blog/2.jpg', readingTime: 8 },
  { slug: 'reservation-en-ligne-avantages', title: { fr: '5 avantages de la réservation en ligne', en: '5 benefits of online booking', es: '5 beneficios de las reservas en línea' }, excerpt: { fr: 'Comment la réservation en ligne transforme votre activité.', en: 'How online booking transforms your business.', es: 'Cómo las reservas en línea transforman tu negocio.' }, category: 'productivite', author: 'Mindzy', date: '2025-01-05', image: '/images/blog/3.jpg', readingTime: 4 },
  { slug: 'google-business-optimisation', title: { fr: 'Optimiser votre fiche Google Business', en: 'Optimize your Google Business Profile', es: 'Optimiza tu perfil de Google Business' }, excerpt: { fr: 'Les étapes pour maximiser votre visibilité locale.', en: 'Steps to maximize your local visibility.', es: 'Pasos para maximizar tu visibilidad local.' }, category: 'seo', author: 'Mindzy', date: '2024-12-28', image: '/images/blog/4.jpg', readingTime: 6 },
  { slug: 'reseaux-sociaux-professionnels', title: { fr: 'Réseaux sociaux : guide pour professionnels', en: 'Social media: guide for professionals', es: 'Redes sociales: guía para profesionales' }, excerpt: { fr: 'Comment utiliser Instagram et LinkedIn pour développer votre activité.', en: 'How to use Instagram and LinkedIn to grow your business.', es: 'Cómo usar Instagram y LinkedIn para hacer crecer tu negocio.' }, category: 'marketing', author: 'Mindzy', date: '2024-12-20', image: '/images/blog/5.jpg', readingTime: 7 },
  { slug: 'creer-site-web-budget', title: { fr: 'Créer un site web professionnel avec un petit budget', en: 'Create a professional website on a budget', es: 'Crea un sitio web profesional con poco presupuesto' }, excerpt: { fr: 'Les solutions pour avoir un site de qualité sans se ruiner.', en: 'Solutions for a quality site without breaking the bank.', es: 'Soluciones para un sitio de calidad sin arruinarse.' }, category: 'business', author: 'Mindzy', date: '2024-12-15', image: '/images/blog/6.jpg', readingTime: 6 },
]

export const faqItems: FAQItem[] = [
  // Général
  { id: 'f1', question: { fr: 'Combien de temps pour créer mon site ?', en: 'How long to create my website?', es: '¿Cuánto tiempo para crear mi sitio?' }, answer: { fr: 'En moyenne 2 à 3 semaines après validation de vos contenus. Pour les projets urgents, nous proposons une option accélérée en 5-7 jours ouvrés avec un supplément.', en: 'On average 2 to 3 weeks after validating your content. For urgent projects, we offer an accelerated option in 5-7 business days with a supplement.', es: 'En promedio 2 a 3 semanas después de validar su contenido. Para proyectos urgentes, ofrecemos una opción acelerada en 5-7 días hábiles con un suplemento.' }, category: 'general' },
  { id: 'f2', question: { fr: 'Dois-je fournir du contenu (textes, images) ?', en: 'Do I need to provide content (texts, images)?', es: '¿Debo proporcionar contenido (textos, imágenes)?' }, answer: { fr: 'Idéalement oui, mais nous pouvons vous accompagner dans la rédaction de vos textes et proposons une banque d\'images professionnelles si nécessaire. Nous offrons également un service de shooting photo pour les plans Business et E-commerce.', en: 'Ideally yes, but we can help you write your texts and offer a professional image library if needed. We also offer a photo shooting service for Business and E-commerce plans.', es: 'Idealmente sí, pero podemos ayudarle a redactar sus textos y ofrecemos una biblioteca de imágenes profesionales si es necesario. También ofrecemos un servicio de sesión fotográfica para los planes Business y E-commerce.' }, category: 'general' },
  { id: 'f3', question: { fr: 'Puis-je voir des exemples de sites que vous avez créés ?', en: 'Can I see examples of sites you\'ve created?', es: '¿Puedo ver ejemplos de sitios que han creado?' }, answer: { fr: 'Absolument ! Consultez notre portfolio avec plus de 40 réalisations dans divers secteurs : restaurants, consultants, artisans, boutiques et bien d\'autres.', en: 'Absolutely! Check out our portfolio with over 40 projects in various sectors: restaurants, consultants, craftsmen, shops and many more.', es: '¡Absolutamente! Consulte nuestro portfolio con más de 40 proyectos en diversos sectores: restaurantes, consultores, artesanos, tiendas y muchos más.' }, category: 'general' },
  { id: 'f4', question: { fr: 'Travaillez-vous avec tous les secteurs d\'activité ?', en: 'Do you work with all business sectors?', es: '¿Trabajan con todos los sectores de actividad?' }, answer: { fr: 'Oui, nous accompagnons tous les entrepreneurs et professionnels : consultants, artisans, restaurants, boutiques, freelances, professions libérales, coachs, et bien d\'autres. Notre expertise s\'adapte à votre métier.', en: 'Yes, we support all entrepreneurs and professionals: consultants, craftsmen, restaurants, shops, freelancers, liberal professions, coaches, and many more. Our expertise adapts to your profession.', es: 'Sí, apoyamos a todos los emprendedores y profesionales: consultores, artesanos, restaurantes, tiendas, freelancers, profesiones liberales, coaches y muchos más. Nuestra experiencia se adapta a su profesión.' }, category: 'general' },

  // Tarification
  { id: 'f5', question: { fr: 'Que comprend l\'abonnement mensuel ?', en: 'What is included in the monthly subscription?', es: '¿Qué incluye la suscripción mensual?' }, answer: { fr: 'L\'abonnement comprend : hébergement premium haute performance, certificat SSL, mises à jour de sécurité, sauvegardes automatiques quotidiennes, support technique prioritaire, et modifications mineures mensuelles (textes, images). Vous n\'avez rien d\'autre à payer.', en: 'The subscription includes: premium high-performance hosting, SSL certificate, security updates, daily automatic backups, priority technical support, and monthly minor modifications (texts, images). You have nothing else to pay.', es: 'La suscripción incluye: alojamiento premium de alto rendimiento, certificado SSL, actualizaciones de seguridad, copias de seguridad automáticas diarias, soporte técnico prioritario y modificaciones menores mensuales (textos, imágenes). No tiene nada más que pagar.' }, category: 'pricing' },
  { id: 'f6', question: { fr: 'Y a-t-il des frais cachés ?', en: 'Are there hidden fees?', es: '¿Hay costos ocultos?' }, answer: { fr: 'Non, jamais. Nos prix sont transparents et tout compris. Le prix affiché inclut la création, l\'hébergement et le support. Seules les fonctionnalités supplémentaires hors forfait (refonte majeure, nouvelles pages, fonctionnalités sur mesure) peuvent entraîner des frais additionnels, toujours devisés à l\'avance.', en: 'No, never. Our prices are transparent and all-inclusive. The displayed price includes creation, hosting and support. Only additional features outside the plan (major redesign, new pages, custom features) may incur additional fees, always quoted in advance.', es: 'No, nunca. Nuestros precios son transparentes y todo incluido. El precio mostrado incluye creación, alojamiento y soporte. Solo las funciones adicionales fuera del plan (rediseño mayor, nuevas páginas, funciones personalizadas) pueden generar cargos adicionales, siempre presupuestados por adelantado.' }, category: 'pricing' },
  { id: 'f7', question: { fr: 'Puis-je changer de formule en cours de route ?', en: 'Can I change my plan later?', es: '¿Puedo cambiar de plan más adelante?' }, answer: { fr: 'Oui, vous pouvez upgrader votre formule à tout moment. Le passage à un plan supérieur est immédiat. Vous ne payez que la différence au prorata.', en: 'Yes, you can upgrade your plan at any time. The switch to a higher plan is immediate. You only pay the difference prorated.', es: 'Sí, puede actualizar su plan en cualquier momento. El cambio a un plan superior es inmediato. Solo paga la diferencia prorrateada.' }, category: 'pricing' },
  { id: 'f8', question: { fr: 'Quels sont les modes de paiement acceptés ?', en: 'What payment methods are accepted?', es: '¿Qué métodos de pago se aceptan?' }, answer: { fr: 'Nous acceptons les cartes bancaires (Visa, Mastercard), les virements SEPA, PayPal et Stripe. Le paiement est mensuel par prélèvement automatique, ou annuel avec 2 mois offerts.', en: 'We accept bank cards (Visa, Mastercard), SEPA transfers, PayPal and Stripe. Payment is monthly by automatic debit, or annual with 2 months free.', es: 'Aceptamos tarjetas bancarias (Visa, Mastercard), transferencias SEPA, PayPal y Stripe. El pago es mensual por débito automático, o anual con 2 meses gratis.' }, category: 'pricing' },
  { id: 'f9', question: { fr: 'Proposez-vous un paiement échelonné pour les frais de création ?', en: 'Do you offer installment payment for setup fees?', es: '¿Ofrecen pago a plazos para los costos de creación?' }, answer: { fr: 'Oui, nous proposons un paiement en 2 ou 3 fois sans frais pour les frais de mise en place. 50% à la commande, et le reste réparti sur les premiers mois.', en: 'Yes, we offer payment in 2 or 3 installments without fees for setup costs. 50% at order, and the rest spread over the first months.', es: 'Sí, ofrecemos pago en 2 o 3 cuotas sin cargos para los costos de instalación. 50% al pedido, y el resto repartido en los primeros meses.' }, category: 'pricing' },

  // Technique
  { id: 'f10', question: { fr: 'Mon site sera-t-il optimisé mobile ?', en: 'Will my site be mobile-optimized?', es: '¿Mi sitio estará optimizado para móvil?' }, answer: { fr: 'Oui, tous nos sites sont 100% responsive et optimisés pour mobile, tablette et desktop. Plus de 60% du trafic web vient du mobile, c\'est donc une priorité absolue dans notre conception.', en: 'Yes, all our sites are 100% responsive and optimized for mobile, tablet and desktop. Over 60% of web traffic comes from mobile, so it\'s an absolute priority in our design.', es: 'Sí, todos nuestros sitios son 100% responsivos y optimizados para móvil, tablet y escritorio. Más del 60% del tráfico web viene del móvil, por lo que es una prioridad absoluta en nuestro diseño.' }, category: 'technical' },
  { id: 'f11', question: { fr: 'Mon site sera-t-il bien référencé sur Google ?', en: 'Will my site rank well on Google?', es: '¿Mi sitio se posicionará bien en Google?' }, answer: { fr: 'Oui, tous nos sites sont construits avec les meilleures pratiques SEO : structure optimisée, balises méta, vitesse de chargement, données structurées, et optimisation Google Business. Nous fournissons également un rapport SEO mensuel.', en: 'Yes, all our sites are built with SEO best practices: optimized structure, meta tags, loading speed, structured data, and Google Business optimization. We also provide a monthly SEO report.', es: 'Sí, todos nuestros sitios están construidos con las mejores prácticas SEO: estructura optimizada, etiquetas meta, velocidad de carga, datos estructurados y optimización de Google Business. También proporcionamos un informe SEO mensual.' }, category: 'technical' },
  { id: 'f12', question: { fr: 'Puis-je avoir un nom de domaine personnalisé ?', en: 'Can I have a custom domain name?', es: '¿Puedo tener un nombre de dominio personalizado?' }, answer: { fr: 'Absolument ! Si vous avez déjà un domaine, nous le configurons gratuitement. Sinon, nous nous occupons de l\'achat et de la configuration (environ 15€/an selon l\'extension choisie).', en: 'Absolutely! If you already have a domain, we configure it for free. Otherwise, we handle the purchase and configuration (about €15/year depending on the extension chosen).', es: '¡Absolutamente! Si ya tiene un dominio, lo configuramos gratis. De lo contrario, nos encargamos de la compra y configuración (aproximadamente 15€/año según la extensión elegida).' }, category: 'technical' },
  { id: 'f13', question: { fr: 'Quelle est la vitesse de chargement de vos sites ?', en: 'What is the loading speed of your sites?', es: '¿Cuál es la velocidad de carga de sus sitios?' }, answer: { fr: 'Nos sites obtiennent généralement un score de 90+ sur Google PageSpeed. Nous utilisons les dernières technologies (Next.js, optimisation d\'images, CDN mondial) pour garantir des temps de chargement ultra-rapides.', en: 'Our sites typically score 90+ on Google PageSpeed. We use the latest technologies (Next.js, image optimization, global CDN) to ensure ultra-fast loading times.', es: 'Nuestros sitios generalmente obtienen una puntuación de 90+ en Google PageSpeed. Utilizamos las últimas tecnologías (Next.js, optimización de imágenes, CDN global) para garantizar tiempos de carga ultrarrápidos.' }, category: 'technical' },
  { id: 'f14', question: { fr: 'Mon site est-il sécurisé ?', en: 'Is my site secure?', es: '¿Mi sitio es seguro?' }, answer: { fr: 'Oui, la sécurité est notre priorité. Tous nos sites incluent : certificat SSL (HTTPS), protection contre les attaques DDoS, sauvegardes quotidiennes automatiques, et mises à jour de sécurité régulières.', en: 'Yes, security is our priority. All our sites include: SSL certificate (HTTPS), DDoS attack protection, automatic daily backups, and regular security updates.', es: 'Sí, la seguridad es nuestra prioridad. Todos nuestros sitios incluyen: certificado SSL (HTTPS), protección contra ataques DDoS, copias de seguridad automáticas diarias y actualizaciones de seguridad regulares.' }, category: 'technical' },

  // Support
  { id: 'f15', question: { fr: 'Proposez-vous un support technique ?', en: 'Do you offer technical support?', es: '¿Ofrecen soporte técnico?' }, answer: { fr: 'Oui, notre équipe support est disponible par email et WhatsApp du lundi au vendredi, 9h-18h. Temps de réponse moyen : moins de 4 heures. Pour les urgences, nous intervenons sous 2 heures.', en: 'Yes, our support team is available via email and WhatsApp Monday to Friday, 9am-6pm. Average response time: less than 4 hours. For emergencies, we intervene within 2 hours.', es: 'Sí, nuestro equipo de soporte está disponible por correo y WhatsApp de lunes a viernes, 9h-18h. Tiempo de respuesta promedio: menos de 4 horas. Para emergencias, intervenimos en menos de 2 horas.' }, category: 'support' },
  { id: 'f16', question: { fr: 'Puis-je modifier mon site moi-même ?', en: 'Can I modify my site myself?', es: '¿Puedo modificar mi sitio yo mismo?' }, answer: { fr: 'Pour les modifications simples (textes, images), vous pouvez nous les envoyer et nous les appliquons sous 24-48h. Pour ceux qui le souhaitent, nous proposons également une interface d\'administration simplifiée (en option).', en: 'For simple modifications (texts, images), you can send them to us and we apply them within 24-48h. For those who want it, we also offer a simplified admin interface (optional).', es: 'Para modificaciones simples (textos, imágenes), puede enviárnoslas y las aplicamos en 24-48h. Para quienes lo deseen, también ofrecemos una interfaz de administración simplificada (opcional).' }, category: 'support' },
  { id: 'f17', question: { fr: 'Que se passe-t-il si je veux arrêter ?', en: 'What happens if I want to stop?', es: '¿Qué pasa si quiero cancelar?' }, answer: { fr: 'Vous êtes libre d\'arrêter à tout moment, sans frais de résiliation. Nous vous fournissons une sauvegarde complète de votre site et pouvons vous aider à migrer vers un autre hébergeur si vous le souhaitez.', en: 'You are free to stop at any time, without termination fees. We provide you with a complete backup of your site and can help you migrate to another host if you wish.', es: 'Es libre de cancelar en cualquier momento, sin cargos de terminación. Le proporcionamos una copia de seguridad completa de su sitio y podemos ayudarle a migrar a otro hosting si lo desea.' }, category: 'support' },

  // Fonctionnalités
  { id: 'f18', question: { fr: 'Comment fonctionne le système de réservation en ligne ?', en: 'How does the online booking system work?', es: '¿Cómo funciona el sistema de reservas en línea?' }, answer: { fr: 'Notre système de réservation est intuitif : vos clients choisissent une date et un créneau disponible, reçoivent une confirmation automatique, et vous êtes notifié instantanément. Synchronisation avec Google Calendar incluse. Rappels automatiques par email/SMS.', en: 'Our booking system is intuitive: your clients choose an available date and slot, receive automatic confirmation, and you are instantly notified. Google Calendar sync included. Automatic email/SMS reminders.', es: 'Nuestro sistema de reservas es intuitivo: sus clientes eligen una fecha y horario disponible, reciben confirmación automática, y usted es notificado instantáneamente. Sincronización con Google Calendar incluida. Recordatorios automáticos por email/SMS.' }, category: 'features' },
  { id: 'f19', question: { fr: 'Puis-je vendre des produits ou services en ligne ?', en: 'Can I sell products or services online?', es: '¿Puedo vender productos o servicios en línea?' }, answer: { fr: 'Oui, avec nos plans Business et E-commerce. Nous intégrons des solutions de paiement sécurisées (Stripe, PayPal) et vous pouvez vendre des produits physiques, des services, des formations, ou des abonnements.', en: 'Yes, with our Business and E-commerce plans. We integrate secure payment solutions (Stripe, PayPal) and you can sell physical products, services, training, or subscriptions.', es: 'Sí, con nuestros planes Business y E-commerce. Integramos soluciones de pago seguras (Stripe, PayPal) y puede vender productos físicos, servicios, formaciones o suscripciones.' }, category: 'features' },
  { id: 'f20', question: { fr: 'Intégrez-vous les réseaux sociaux ?', en: 'Do you integrate social media?', es: '¿Integran las redes sociales?' }, answer: { fr: 'Oui, nous intégrons vos réseaux sociaux (Instagram, Facebook, LinkedIn, TikTok) directement sur votre site : flux Instagram, boutons de partage, liens vers vos profils, et widgets interactifs.', en: 'Yes, we integrate your social media (Instagram, Facebook, LinkedIn, TikTok) directly on your site: Instagram feed, share buttons, links to your profiles, and interactive widgets.', es: 'Sí, integramos sus redes sociales (Instagram, Facebook, LinkedIn, TikTok) directamente en su sitio: feed de Instagram, botones de compartir, enlaces a sus perfiles y widgets interactivos.' }, category: 'features' },
  { id: 'f21', question: { fr: 'Puis-je avoir un blog sur mon site ?', en: 'Can I have a blog on my site?', es: '¿Puedo tener un blog en mi sitio?' }, answer: { fr: 'Oui, nous incluons un blog optimisé SEO dans tous nos plans (sauf Basic). Vous pouvez nous envoyer vos articles et nous les publions, ou opter pour notre service de rédaction (articles optimisés SEO sur votre thématique).', en: 'Yes, we include an SEO-optimized blog in all our plans (except Basic). You can send us your articles and we publish them, or opt for our writing service (SEO-optimized articles on your topic).', es: 'Sí, incluimos un blog optimizado SEO en todos nuestros planes (excepto Basic). Puede enviarnos sus artículos y los publicamos, u optar por nuestro servicio de redacción (artículos optimizados SEO sobre su temática).' }, category: 'features' },
  { id: 'f22', question: { fr: 'Proposez-vous des formulaires de contact ?', en: 'Do you offer contact forms?', es: '¿Ofrecen formularios de contacto?' }, answer: { fr: 'Oui, chaque site inclut un formulaire de contact professionnel avec protection anti-spam. Vous recevez les messages directement par email et pouvez personnaliser les champs selon vos besoins.', en: 'Yes, each site includes a professional contact form with anti-spam protection. You receive messages directly by email and can customize fields according to your needs.', es: 'Sí, cada sitio incluye un formulario de contacto profesional con protección anti-spam. Recibe los mensajes directamente por correo y puede personalizar los campos según sus necesidades.' }, category: 'features' },
  { id: 'f23', question: { fr: 'Puis-je avoir plusieurs langues sur mon site ?', en: 'Can I have multiple languages on my site?', es: '¿Puedo tener varios idiomas en mi sitio?' }, answer: { fr: 'Oui, nous proposons des sites multilingues (français, anglais, espagnol, et autres sur demande). Chaque langue dispose de son propre contenu optimisé et d\'une URL dédiée pour le SEO.', en: 'Yes, we offer multilingual sites (French, English, Spanish, and others on request). Each language has its own optimized content and dedicated URL for SEO.', es: 'Sí, ofrecemos sitios multilingües (francés, inglés, español y otros bajo pedido). Cada idioma tiene su propio contenido optimizado y URL dedicada para SEO.' }, category: 'features' },

  // Processus
  { id: 'f24', question: { fr: 'Comment se déroule la création de mon site ?', en: 'How does the site creation process work?', es: '¿Cómo es el proceso de creación de mi sitio?' }, answer: { fr: '1. Appel découverte (30 min) pour comprendre vos besoins. 2. Proposition personnalisée sous 48h. 3. Création et première maquette sous 1 semaine. 4. Vos retours et ajustements. 5. Mise en ligne après validation. 6. Formation et support continu.', en: '1. Discovery call (30 min) to understand your needs. 2. Custom proposal within 48h. 3. Creation and first mockup within 1 week. 4. Your feedback and adjustments. 5. Launch after validation. 6. Training and ongoing support.', es: '1. Llamada de descubrimiento (30 min) para entender sus necesidades. 2. Propuesta personalizada en 48h. 3. Creación y primera maqueta en 1 semana. 4. Sus comentarios y ajustes. 5. Lanzamiento tras validación. 6. Formación y soporte continuo.' }, category: 'process' },
  { id: 'f25', question: { fr: 'Combien de modifications puis-je demander ?', en: 'How many modifications can I request?', es: '¿Cuántas modificaciones puedo solicitar?' }, answer: { fr: 'Pendant la création, vous avez droit à 2 rounds de révisions majeures inclus. Après le lancement, les modifications mineures (textes, images) sont illimitées et incluses dans votre abonnement. Les modifications structurelles sont devisées.', en: 'During creation, you are entitled to 2 rounds of major revisions included. After launch, minor modifications (texts, images) are unlimited and included in your subscription. Structural modifications are quoted.', es: 'Durante la creación, tiene derecho a 2 rondas de revisiones mayores incluidas. Después del lanzamiento, las modificaciones menores (textos, imágenes) son ilimitadas e incluidas en su suscripción. Las modificaciones estructurales se presupuestan.' }, category: 'process' },
]

export const diagnosticQuestions: DiagnosticQuestion[] = [
  { id: 'has-website', question: { fr: 'Avez-vous déjà un site web ?', en: 'Do you already have a website?', es: '¿Ya tiene un sitio web?' }, options: [{ value: 'yes', label: { fr: 'Oui', en: 'Yes', es: 'Sí' }, score: 2 }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, score: 0 }, { value: 'outdated', label: { fr: 'Oui, mais obsolète', en: 'Yes, but outdated', es: 'Sí, pero desactualizado' }, score: 1 }] },
  { id: 'has-booking', question: { fr: 'Avez-vous un système de réservation en ligne ?', en: 'Do you have online booking?', es: '¿Tiene reservas en línea?' }, options: [{ value: 'yes', label: { fr: 'Oui', en: 'Yes', es: 'Sí' }, score: 2 }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, score: 0 }, { value: 'basic', label: { fr: 'Basique', en: 'Basic', es: 'Básico' }, score: 1 }] },
  { id: 'has-gmb', question: { fr: 'Avez-vous une fiche Google Business ?', en: 'Do you have a Google Business profile?', es: '¿Tiene perfil de Google Business?' }, options: [{ value: 'yes-opt', label: { fr: 'Oui, optimisée', en: 'Yes, optimized', es: 'Sí, optimizado' }, score: 2 }, { value: 'yes-basic', label: { fr: 'Oui, pas optimisée', en: 'Yes, not optimized', es: 'Sí, no optimizado' }, score: 1 }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, score: 0 }] },
  { id: 'weekly-requests', question: { fr: 'Combien de demandes de RDV par semaine ?', en: 'How many appointment requests per week?', es: '¿Cuántas solicitudes de cita por semana?' }, options: [{ value: 'many', label: { fr: 'Plus de 10', en: 'More than 10', es: 'Más de 10' }, score: 2 }, { value: 'some', label: { fr: '5 à 10', en: '5 to 10', es: '5 a 10' }, score: 1 }, { value: 'few', label: { fr: 'Moins de 5', en: 'Less than 5', es: 'Menos de 5' }, score: 0 }] },
]

export const customDiagnosticQuestions: DiagnosticQuestion[] = [
  {
    id: 'platform-type',
    question: { fr: 'Quel type de projet souhaitez-vous développer ?', en: 'What type of project do you want to develop?', es: '¿Qué tipo de proyecto desea desarrollar?' },
    options: [
      { value: 'web-app', label: { fr: 'Application web (SaaS, plateforme, dashboard)', en: 'Web application (SaaS, platform, dashboard)', es: 'Aplicación web (SaaS, plataforma, dashboard)' }, score: 2 },
      { value: 'mobile-app', label: { fr: 'Application mobile native (iOS ou Android)', en: 'Native mobile app (iOS or Android)', es: 'App móvil nativa (iOS o Android)' }, score: 2 },
      { value: 'cross-platform', label: { fr: 'Application cross-plateforme (iOS + Android + Web)', en: 'Cross-platform app (iOS + Android + Web)', es: 'App multiplataforma (iOS + Android + Web)' }, score: 2 },
      { value: 'unsure', label: { fr: 'Je ne sais pas encore', en: "I'm not sure yet", es: 'Aún no estoy seguro' }, score: 0 },
    ],
  },
  {
    id: 'project-maturity',
    question: { fr: 'Quel est le niveau de maturité de votre projet ?', en: 'How mature is your project?', es: '¿Cuál es el nivel de madurez de su proyecto?' },
    options: [
      { value: 'idea', label: { fr: 'Juste une idée, rien de concret', en: 'Just an idea, nothing concrete', es: 'Solo una idea, nada concreto' }, score: 0 },
      { value: 'validated', label: { fr: 'Idée validée avec des utilisateurs potentiels', en: 'Idea validated with potential users', es: 'Idea validada con usuarios potenciales' }, score: 1 },
      { value: 'specs', label: { fr: 'Cahier des charges ou maquettes prêtes', en: 'Specifications or mockups ready', es: 'Especificaciones o maquetas listas' }, score: 2 },
      { value: 'mvp', label: { fr: 'MVP existant à améliorer / refondre', en: 'Existing MVP to improve / redesign', es: 'MVP existente a mejorar / rediseñar' }, score: 2 },
    ],
  },
  {
    id: 'technical-complexity',
    question: { fr: 'Quelles fonctionnalités techniques clés sont nécessaires ?', en: 'What key technical features are needed?', es: '¿Qué funcionalidades técnicas clave se necesitan?' },
    options: [
      { value: 'simple', label: { fr: 'CRUD basique (formulaires, listes, profils)', en: 'Basic CRUD (forms, lists, profiles)', es: 'CRUD básico (formularios, listas, perfiles)' }, score: 0 },
      { value: 'moderate', label: { fr: 'Auth + API tierces + paiements', en: 'Auth + third-party APIs + payments', es: 'Auth + APIs de terceros + pagos' }, score: 1 },
      { value: 'advanced', label: { fr: 'Temps réel, IA, géolocalisation, chat', en: 'Real-time, AI, geolocation, chat', es: 'Tiempo real, IA, geolocalización, chat' }, score: 2 },
      { value: 'enterprise', label: { fr: 'Multi-tenant, microservices, scalabilité', en: 'Multi-tenant, microservices, scalability', es: 'Multi-tenant, microservicios, escalabilidad' }, score: 2 },
    ],
  },
  {
    id: 'target-audience',
    question: { fr: 'Qui utilisera votre application ?', en: 'Who will use your application?', es: '¿Quién usará su aplicación?' },
    options: [
      { value: 'b2c', label: { fr: 'Grand public (B2C)', en: 'Consumers (B2C)', es: 'Público general (B2C)' }, score: 2 },
      { value: 'b2b', label: { fr: 'Entreprises / Professionnels (B2B)', en: 'Businesses / Professionals (B2B)', es: 'Empresas / Profesionales (B2B)' }, score: 2 },
      { value: 'internal', label: { fr: 'Outil interne pour mon équipe', en: 'Internal tool for my team', es: 'Herramienta interna para mi equipo' }, score: 1 },
      { value: 'marketplace', label: { fr: 'Marketplace / Mise en relation', en: 'Marketplace / Connecting users', es: 'Marketplace / Conexión de usuarios' }, score: 2 },
    ],
  },
  {
    id: 'timeline-budget',
    question: { fr: 'Quel est votre horizon de lancement ?', en: 'What is your launch timeline?', es: '¿Cuál es su horizonte de lanzamiento?' },
    options: [
      { value: 'urgent', label: { fr: 'Moins d\'1 mois — urgent', en: 'Less than 1 month — urgent', es: 'Menos de 1 mes — urgente' }, score: 2 },
      { value: 'normal', label: { fr: '1 à 3 mois', en: '1 to 3 months', es: '1 a 3 meses' }, score: 2 },
      { value: 'flexible', label: { fr: '3 à 6 mois', en: '3 to 6 months', es: '3 a 6 meses' }, score: 1 },
      { value: 'exploring', label: { fr: 'En exploration, pas de deadline', en: 'Exploring, no deadline', es: 'En exploración, sin fecha límite' }, score: 0 },
    ],
  },
  {
    id: 'existing-tech',
    question: { fr: 'Avez-vous déjà une base technique existante ?', en: 'Do you already have an existing technical foundation?', es: '¿Ya tiene una base técnica existente?' },
    options: [
      { value: 'nothing', label: { fr: 'Rien, je pars de zéro', en: 'Nothing, starting from scratch', es: 'Nada, parto de cero' }, score: 0 },
      { value: 'design', label: { fr: 'Maquettes UI/UX (Figma, etc.)', en: 'UI/UX mockups (Figma, etc.)', es: 'Maquetas UI/UX (Figma, etc.)' }, score: 1 },
      { value: 'prototype', label: { fr: 'Prototype / MVP fonctionnel', en: 'Working prototype / MVP', es: 'Prototipo / MVP funcional' }, score: 2 },
      { value: 'full-app', label: { fr: 'Application complète à refondre', en: 'Full application to redesign', es: 'Aplicación completa a rediseñar' }, score: 2 },
    ],
  },
]

export const profileKeys = ['beginner', 'pro', 'booking', 'sales', 'custom'] as const
export type ProfileKey = (typeof profileKeys)[number]

export const profileQuestions: Record<ProfileKey, ProfileQuestion[]> = {
  beginner: [
    { id: 'profession', question: { fr: 'Quelle est votre profession ?', en: 'What is your profession?', es: '¿Cuál es su profesión?' }, options: [{ value: 'therapist', label: { fr: 'Thérapeute / Praticien bien-être', en: 'Therapist / Wellness practitioner', es: 'Terapeuta / Practicante de bienestar' }, icon: '🧘' }, { value: 'coach', label: { fr: 'Coach / Consultant', en: 'Coach / Consultant', es: 'Coach / Consultor' }, icon: '💼' }, { value: 'artisan', label: { fr: 'Artisan / Créateur', en: 'Craftsman / Creator', es: 'Artesano / Creador' }, icon: '🛠️' }, { value: 'restaurant', label: { fr: 'Restaurateur / Commerce', en: 'Restaurant / Retail', es: 'Restaurante / Comercio' }, icon: '🍽️' }, { value: 'other', label: { fr: 'Autre profession', en: 'Other profession', es: 'Otra profesión' }, icon: '✨' }] },
    { id: 'online-presence', question: { fr: 'Avez-vous déjà une présence en ligne ?', en: 'Do you already have an online presence?', es: '¿Ya tiene presencia en línea?' }, options: [{ value: 'nothing', label: { fr: 'Rien du tout', en: 'Nothing at all', es: 'Nada en absoluto' }, icon: '🆕' }, { value: 'social-only', label: { fr: 'Réseaux sociaux uniquement', en: 'Social media only', es: 'Solo redes sociales' }, icon: '📱' }, { value: 'gmb', label: { fr: 'Fiche Google Business', en: 'Google Business Profile', es: 'Perfil de Google Business' }, icon: '📍' }, { value: 'basic-page', label: { fr: 'Page simple (Wix, etc.)', en: 'Simple page (Wix, etc.)', es: 'Página simple (Wix, etc.)' }, icon: '📄' }] },
    { id: 'timeline', question: { fr: 'Quand souhaitez-vous lancer votre site ?', en: 'When do you want to launch your site?', es: '¿Cuándo quiere lanzar su sitio?' }, options: [{ value: 'asap', label: { fr: 'Dès que possible', en: 'As soon as possible', es: 'Lo antes posible' }, icon: '🚀' }, { value: '1-3months', label: { fr: 'Dans 1 à 3 mois', en: 'In 1 to 3 months', es: 'En 1 a 3 meses' }, icon: '📅' }, { value: '3-6months', label: { fr: 'Dans 3 à 6 mois', en: 'In 3 to 6 months', es: 'En 3 a 6 meses' }, icon: '🗓️' }, { value: 'unsure', label: { fr: 'Pas encore décidé', en: 'Not decided yet', es: 'Aún no decidido' }, icon: '🤔' }] },
    { id: 'priority', question: { fr: 'Qu\'est-ce qui est le plus important pour vous ?', en: 'What matters most to you?', es: '¿Qué es lo más importante para usted?' }, options: [{ value: 'image', label: { fr: 'Image professionnelle', en: 'Professional image', es: 'Imagen profesional' }, icon: '✨' }, { value: 'bookings', label: { fr: 'Réservations en ligne', en: 'Online bookings', es: 'Reservas en línea' }, icon: '📅' }, { value: 'seo', label: { fr: 'Visibilité sur Google', en: 'Google visibility', es: 'Visibilidad en Google' }, icon: '🔍' }, { value: 'all', label: { fr: 'Tout en même temps', en: 'All of the above', es: 'Todo a la vez' }, icon: '🎯' }] },
    { id: 'budget', question: { fr: 'Quel budget envisagez-vous ?', en: 'What budget are you considering?', es: '¿Qué presupuesto considera?' }, options: [{ value: '<1000', label: { fr: 'Moins de 1 000 €', en: 'Less than €1,000', es: 'Menos de 1.000 €' }, icon: '💰' }, { value: '1000-2000', label: { fr: '1 000 € - 2 000 €', en: '€1,000 - €2,000', es: '1.000 € - 2.000 €' }, icon: '💰' }, { value: '2000-5000', label: { fr: '2 000 € - 5 000 €', en: '€2,000 - €5,000', es: '2.000 € - 5.000 €' }, icon: '💎' }, { value: '5000+', label: { fr: 'Plus de 5 000 €', en: 'More than €5,000', es: 'Más de 5.000 €' }, icon: '💎' }] },
  ],
  pro: [
    { id: 'site-type', question: { fr: 'Quel type de site avez-vous actuellement ?', en: 'What type of website do you currently have?', es: '¿Qué tipo de sitio tiene actualmente?' }, options: [{ value: 'wordpress', label: { fr: 'WordPress', en: 'WordPress', es: 'WordPress' }, icon: '🔧' }, { value: 'wix-squarespace', label: { fr: 'Wix / Squarespace', en: 'Wix / Squarespace', es: 'Wix / Squarespace' }, icon: '🧩' }, { value: 'custom', label: { fr: 'Site sur-mesure', en: 'Custom website', es: 'Sitio personalizado' }, icon: '💻' }, { value: 'other', label: { fr: 'Autre / Je ne sais pas', en: 'Other / I don\'t know', es: 'Otro / No sé' }, icon: '❓' }] },
    { id: 'main-issue', question: { fr: 'Quel est le principal problème de votre site ?', en: 'What is the main issue with your site?', es: '¿Cuál es el problema principal de su sitio?' }, options: [{ value: 'outdated', label: { fr: 'Design obsolète', en: 'Outdated design', es: 'Diseño obsoleto' }, icon: '🎨' }, { value: 'slow', label: { fr: 'Trop lent', en: 'Too slow', es: 'Demasiado lento' }, icon: '🐌' }, { value: 'not-mobile', label: { fr: 'Pas adapté mobile', en: 'Not mobile-friendly', es: 'No adaptado a móvil' }, icon: '📱' }, { value: 'no-seo', label: { fr: 'Invisible sur Google', en: 'Invisible on Google', es: 'Invisible en Google' }, icon: '👻' }, { value: 'low-conversion', label: { fr: 'Peu de conversions', en: 'Low conversions', es: 'Pocas conversiones' }, icon: '📉' }] },
    { id: 'features-needed', question: { fr: 'De quelles fonctionnalités avez-vous besoin ?', en: 'What features do you need?', es: '¿Qué funcionalidades necesita?' }, options: [{ value: 'modern-design', label: { fr: 'Design moderne', en: 'Modern design', es: 'Diseño moderno' }, icon: '✨' }, { value: 'booking', label: { fr: 'Réservation en ligne', en: 'Online booking', es: 'Reservas en línea' }, icon: '📅' }, { value: 'ecommerce', label: { fr: 'Vente en ligne', en: 'E-commerce', es: 'Venta en línea' }, icon: '🛒' }, { value: 'blog-seo', label: { fr: 'Blog & SEO', en: 'Blog & SEO', es: 'Blog y SEO' }, icon: '📝' }, { value: 'all', label: { fr: 'Tout ça !', en: 'All of the above!', es: '¡Todo eso!' }, icon: '🎯' }] },
    { id: 'urgency', question: { fr: 'Quelle est l\'urgence de la refonte ?', en: 'How urgent is the redesign?', es: '¿Qué tan urgente es el rediseño?' }, options: [{ value: 'asap', label: { fr: 'Urgent, dès que possible', en: 'Urgent, ASAP', es: 'Urgente, lo antes posible' }, icon: '🔥' }, { value: '1-3months', label: { fr: 'Dans 1 à 3 mois', en: 'In 1 to 3 months', es: 'En 1 a 3 meses' }, icon: '📅' }, { value: '3-6months', label: { fr: 'Dans 3 à 6 mois', en: 'In 3 to 6 months', es: 'En 3 a 6 meses' }, icon: '🗓️' }, { value: 'exploring', label: { fr: 'Je me renseigne', en: 'Just exploring', es: 'Solo me informo' }, icon: '🔎' }] },
    { id: 'budget', question: { fr: 'Quel budget envisagez-vous ?', en: 'What budget are you considering?', es: '¿Qué presupuesto considera?' }, options: [{ value: '<1000', label: { fr: 'Moins de 1 000 €', en: 'Less than €1,000', es: 'Menos de 1.000 €' }, icon: '💰' }, { value: '1000-2000', label: { fr: '1 000 € - 2 000 €', en: '€1,000 - €2,000', es: '1.000 € - 2.000 €' }, icon: '💰' }, { value: '2000-5000', label: { fr: '2 000 € - 5 000 €', en: '€2,000 - €5,000', es: '2.000 € - 5.000 €' }, icon: '💎' }, { value: '5000+', label: { fr: 'Plus de 5 000 €', en: 'More than €5,000', es: 'Más de 5.000 €' }, icon: '💎' }] },
  ],
  booking: [
    { id: 'profession', question: { fr: 'Quelle est votre profession ?', en: 'What is your profession?', es: '¿Cuál es su profesión?' }, options: [{ value: 'therapist', label: { fr: 'Thérapeute / Praticien', en: 'Therapist / Practitioner', es: 'Terapeuta / Practicante' }, icon: '🧘' }, { value: 'coach', label: { fr: 'Coach / Consultant', en: 'Coach / Consultant', es: 'Coach / Consultor' }, icon: '💼' }, { value: 'beauty', label: { fr: 'Beauté / Bien-être', en: 'Beauty / Wellness', es: 'Belleza / Bienestar' }, icon: '💆' }, { value: 'medical', label: { fr: 'Professionnel de santé', en: 'Healthcare professional', es: 'Profesional de salud' }, icon: '🏥' }, { value: 'other', label: { fr: 'Autre', en: 'Other', es: 'Otro' }, icon: '✨' }] },
    { id: 'current-method', question: { fr: 'Comment gérez-vous vos RDV aujourd\'hui ?', en: 'How do you manage appointments today?', es: '¿Cómo gestiona sus citas hoy?' }, options: [{ value: 'phone', label: { fr: 'Téléphone', en: 'Phone', es: 'Teléfono' }, icon: '📞' }, { value: 'email', label: { fr: 'Email / Messages', en: 'Email / Messages', es: 'Email / Mensajes' }, icon: '📧' }, { value: 'social', label: { fr: 'Réseaux sociaux', en: 'Social media', es: 'Redes sociales' }, icon: '📱' }, { value: 'paper', label: { fr: 'Agenda papier', en: 'Paper agenda', es: 'Agenda de papel' }, icon: '📓' }, { value: 'tool', label: { fr: 'Un outil en ligne (Doctolib, etc.)', en: 'An online tool (Doctolib, etc.)', es: 'Una herramienta online (Doctolib, etc.)' }, icon: '🔧' }] },
    { id: 'monthly-appointments', question: { fr: 'Combien de RDV prenez-vous par mois ?', en: 'How many appointments do you take per month?', es: '¿Cuántas citas tiene por mes?' }, options: [{ value: '<20', label: { fr: 'Moins de 20', en: 'Less than 20', es: 'Menos de 20' }, icon: '📊' }, { value: '20-50', label: { fr: '20 à 50', en: '20 to 50', es: '20 a 50' }, icon: '📊' }, { value: '50-100', label: { fr: '50 à 100', en: '50 to 100', es: '50 a 100' }, icon: '📈' }, { value: '100+', label: { fr: 'Plus de 100', en: 'More than 100', es: 'Más de 100' }, icon: '🚀' }] },
    { id: 'automation-needs', question: { fr: 'Que souhaitez-vous automatiser ?', en: 'What do you want to automate?', es: '¿Qué quiere automatizar?' }, options: [{ value: 'booking-only', label: { fr: 'Prise de RDV uniquement', en: 'Bookings only', es: 'Solo citas' }, icon: '📅' }, { value: 'booking-payments', label: { fr: 'RDV + paiements en ligne', en: 'Bookings + online payments', es: 'Citas + pagos en línea' }, icon: '💳' }, { value: 'full-crm', label: { fr: 'Gestion complète (RDV, clients, rappels)', en: 'Full management (bookings, clients, reminders)', es: 'Gestión completa (citas, clientes, recordatorios)' }, icon: '🎛️' }, { value: 'unsure', label: { fr: 'Je ne sais pas encore', en: 'Not sure yet', es: 'Aún no sé' }, icon: '🤔' }] },
    { id: 'has-website', question: { fr: 'Avez-vous déjà un site web ?', en: 'Do you already have a website?', es: '¿Ya tiene un sitio web?' }, options: [{ value: 'yes', label: { fr: 'Oui, à jour', en: 'Yes, up to date', es: 'Sí, actualizado' }, icon: '✅' }, { value: 'yes-outdated', label: { fr: 'Oui, mais obsolète', en: 'Yes, but outdated', es: 'Sí, pero obsoleto' }, icon: '⚠️' }, { value: 'no', label: { fr: 'Non, pas encore', en: 'No, not yet', es: 'No, todavía no' }, icon: '🆕' }] },
  ],
  sales: [
    { id: 'product-type', question: { fr: 'Que souhaitez-vous vendre ?', en: 'What do you want to sell?', es: '¿Qué quiere vender?' }, options: [{ value: 'physical', label: { fr: 'Produits physiques', en: 'Physical products', es: 'Productos físicos' }, icon: '📦' }, { value: 'digital', label: { fr: 'Produits numériques', en: 'Digital products', es: 'Productos digitales' }, icon: '💻' }, { value: 'services', label: { fr: 'Services / Prestations', en: 'Services', es: 'Servicios' }, icon: '🤝' }, { value: 'mixed', label: { fr: 'Un peu de tout', en: 'A mix of everything', es: 'Un poco de todo' }, icon: '🎯' }] },
    { id: 'product-count', question: { fr: 'Combien de produits/services proposez-vous ?', en: 'How many products/services do you offer?', es: '¿Cuántos productos/servicios ofrece?' }, options: [{ value: '<10', label: { fr: 'Moins de 10', en: 'Less than 10', es: 'Menos de 10' }, icon: '📊' }, { value: '10-50', label: { fr: '10 à 50', en: '10 to 50', es: '10 a 50' }, icon: '📊' }, { value: '50-200', label: { fr: '50 à 200', en: '50 to 200', es: '50 a 200' }, icon: '📈' }, { value: '200+', label: { fr: 'Plus de 200', en: 'More than 200', es: 'Más de 200' }, icon: '🚀' }] },
    { id: 'current-sales', question: { fr: 'Comment vendez-vous actuellement ?', en: 'How do you currently sell?', es: '¿Cómo vende actualmente?' }, options: [{ value: 'nowhere', label: { fr: 'Je ne vends pas encore en ligne', en: 'I don\'t sell online yet', es: 'Aún no vendo en línea' }, icon: '🆕' }, { value: 'social', label: { fr: 'Via les réseaux sociaux', en: 'Via social media', es: 'A través de redes sociales' }, icon: '📱' }, { value: 'marketplace', label: { fr: 'Marketplace (Etsy, Amazon...)', en: 'Marketplace (Etsy, Amazon...)', es: 'Marketplace (Etsy, Amazon...)' }, icon: '🏪' }, { value: 'own-site', label: { fr: 'Mon propre site', en: 'My own website', es: 'Mi propio sitio' }, icon: '🌐' }] },
    { id: 'payment-needs', question: { fr: 'Quels moyens de paiement souhaitez-vous ?', en: 'What payment methods do you want?', es: '¿Qué métodos de pago desea?' }, options: [{ value: 'card', label: { fr: 'Carte bancaire', en: 'Credit card', es: 'Tarjeta bancaria' }, icon: '💳' }, { value: 'multiple', label: { fr: 'Carte + PayPal + virement', en: 'Card + PayPal + transfer', es: 'Tarjeta + PayPal + transferencia' }, icon: '🔄' }, { value: 'subscription', label: { fr: 'Paiements récurrents / Abonnements', en: 'Recurring / Subscriptions', es: 'Pagos recurrentes / Suscripciones' }, icon: '🔁' }, { value: 'unsure', label: { fr: 'Je ne sais pas encore', en: 'Not sure yet', es: 'Aún no sé' }, icon: '🤔' }] },
    { id: 'budget', question: { fr: 'Quel budget envisagez-vous ?', en: 'What budget are you considering?', es: '¿Qué presupuesto considera?' }, options: [{ value: '<1000', label: { fr: 'Moins de 1 000 €', en: 'Less than €1,000', es: 'Menos de 1.000 €' }, icon: '💰' }, { value: '1000-2000', label: { fr: '1 000 € - 2 000 €', en: '€1,000 - €2,000', es: '1.000 € - 2.000 €' }, icon: '💰' }, { value: '2000-5000', label: { fr: '2 000 € - 5 000 €', en: '€2,000 - €5,000', es: '2.000 € - 5.000 €' }, icon: '💎' }, { value: '5000+', label: { fr: 'Plus de 5 000 €', en: 'More than €5,000', es: 'Más de 5.000 €' }, icon: '💎' }] },
  ],
  custom: [
    { id: 'project-type', question: { fr: 'Quel type de projet souhaitez-vous réaliser ?', en: 'What type of project do you want to build?', es: '¿Qué tipo de proyecto quiere crear?' }, options: [{ value: 'web-app', label: { fr: 'Application web (SaaS, plateforme, dashboard)', en: 'Web application (SaaS, platform, dashboard)', es: 'Aplicación web (SaaS, plataforma, dashboard)' }, icon: '🌐' }, { value: 'mobile-app', label: { fr: 'Application mobile (iOS / Android)', en: 'Mobile app (iOS / Android)', es: 'Aplicación móvil (iOS / Android)' }, icon: '📱' }, { value: 'cross-platform', label: { fr: 'Application cross-plateforme (iOS + Android + Web)', en: 'Cross-platform app (iOS + Android + Web)', es: 'App multiplataforma (iOS + Android + Web)' }, icon: '🔄' }, { value: 'unsure', label: { fr: 'Je ne suis pas encore sûr', en: "I'm not sure yet", es: 'Aún no estoy seguro' }, icon: '🤔' }] },
    { id: 'project-stage', question: { fr: 'À quel stade en est votre projet ?', en: 'What stage is your project at?', es: '¿En qué etapa se encuentra su proyecto?' }, options: [{ value: 'idea', label: { fr: "J'ai une idée, pas encore de specs", en: 'I have an idea, no specs yet', es: 'Tengo una idea, sin especificaciones aún' }, icon: '💡' }, { value: 'specs-ready', label: { fr: "J'ai un cahier des charges / maquettes", en: 'I have specifications / mockups', es: 'Tengo especificaciones / maquetas' }, icon: '📋' }, { value: 'mvp-exists', label: { fr: "J'ai un MVP à améliorer", en: 'I have an MVP to improve', es: 'Tengo un MVP que mejorar' }, icon: '🛠️' }, { value: 'redesign', label: { fr: "J'ai une app existante à refondre", en: 'I have an existing app to redesign', es: 'Tengo una app existente que rediseñar' }, icon: '♻️' }] },
    { id: 'target-users', question: { fr: 'Qui sont les utilisateurs cibles ?', en: 'Who are the target users?', es: '¿Quiénes son los usuarios objetivo?' }, options: [{ value: 'b2c', label: { fr: 'Grand public (B2C)', en: 'Consumers (B2C)', es: 'Público general (B2C)' }, icon: '👥' }, { value: 'b2b', label: { fr: 'Entreprises (B2B)', en: 'Businesses (B2B)', es: 'Empresas (B2B)' }, icon: '🏢' }, { value: 'internal', label: { fr: 'Outil interne (mon équipe)', en: 'Internal tool (my team)', es: 'Herramienta interna (mi equipo)' }, icon: '🔒' }, { value: 'marketplace', label: { fr: 'Marketplace (mise en relation)', en: 'Marketplace (connecting users)', es: 'Marketplace (conectar usuarios)' }, icon: '🤝' }] },
    { id: 'key-features', question: { fr: 'Quelle fonctionnalité clé est prioritaire ?', en: 'What key feature is a priority?', es: '¿Qué funcionalidad clave es prioritaria?' }, options: [{ value: 'auth-dashboard', label: { fr: 'Authentification + espace utilisateur', en: 'Authentication + user dashboard', es: 'Autenticación + panel de usuario' }, icon: '🔐' }, { value: 'payments', label: { fr: 'Paiements / abonnements', en: 'Payments / subscriptions', es: 'Pagos / suscripciones' }, icon: '💳' }, { value: 'realtime', label: { fr: 'Temps réel (chat, notifications)', en: 'Real-time (chat, notifications)', es: 'Tiempo real (chat, notificaciones)' }, icon: '⚡' }, { value: 'integrations', label: { fr: 'Intégrations API tierces', en: 'Third-party API integrations', es: 'Integraciones API de terceros' }, icon: '🔗' }, { value: 'ai', label: { fr: 'Intelligence artificielle / IA', en: 'Artificial intelligence / AI', es: 'Inteligencia artificial / IA' }, icon: '🤖' }] },
    { id: 'timeline', question: { fr: 'Quel est votre délai souhaité ?', en: 'What is your desired timeline?', es: '¿Cuál es su plazo deseado?' }, options: [{ value: '<1month', label: { fr: 'Moins d\'1 mois', en: 'Less than 1 month', es: 'Menos de 1 mes' }, icon: '🔥' }, { value: '1-3months', label: { fr: '1 à 3 mois', en: '1 to 3 months', es: '1 a 3 meses' }, icon: '📅' }, { value: '3-6months', label: { fr: '3 à 6 mois', en: '3 to 6 months', es: '3 a 6 meses' }, icon: '🗓️' }, { value: '6months+', label: { fr: 'Plus de 6 mois / en exploration', en: '6+ months / just exploring', es: '6+ meses / en exploración' }, icon: '🔎' }] },
    { id: 'budget', question: { fr: 'Quel budget envisagez-vous pour ce projet ?', en: 'What budget are you considering for this project?', es: '¿Qué presupuesto considera para este proyecto?' }, options: [{ value: '<5000', label: { fr: 'Moins de 5 000 €', en: 'Less than €5,000', es: 'Menos de 5.000 €' }, icon: '💰' }, { value: '5000-10000', label: { fr: '5 000 € - 10 000 €', en: '€5,000 - €10,000', es: '5.000 € - 10.000 €' }, icon: '💰' }, { value: '10000-25000', label: { fr: '10 000 € - 25 000 €', en: '€10,000 - €25,000', es: '10.000 € - 25.000 €' }, icon: '💎' }, { value: '25000+', label: { fr: 'Plus de 25 000 €', en: 'More than €25,000', es: 'Más de 25.000 €' }, icon: '💎' }] },
  ],
}

export const onboardingSteps: OnboardingStep[] = [
  { id: 'objective', question: { fr: 'Quel est votre objectif principal ?', en: 'What is your main objective?', es: '¿Cuál es su objetivo principal?' }, options: [{ value: 'visibility', label: { fr: 'Gagner en visibilité', en: 'Increase visibility', es: 'Aumentar visibilidad' }, icon: '👁️' }, { value: 'booking', label: { fr: 'Automatiser les réservations', en: 'Automate bookings', es: 'Automatizar reservas' }, icon: '📅' }, { value: 'sales', label: { fr: 'Vendre des produits/services', en: 'Sell products/services', es: 'Vender productos/servicios' }, icon: '💰' }, { value: 'credibility', label: { fr: 'Renforcer ma crédibilité', en: 'Strengthen credibility', es: 'Fortalecer credibilidad' }, icon: '🏆' }] },
  { id: 'assets', question: { fr: 'Quels éléments de marque avez-vous ?', en: 'What brand elements do you have?', es: '¿Qué elementos de marca tiene?' }, options: [{ value: 'logo', label: { fr: 'Logo professionnel', en: 'Professional logo', es: 'Logo profesional' }, icon: '🎨' }, { value: 'colors', label: { fr: 'Charte graphique', en: 'Brand guidelines', es: 'Guía de marca' }, icon: '🎯' }, { value: 'nothing', label: { fr: 'Rien pour l\'instant', en: 'Nothing yet', es: 'Nada por ahora' }, icon: '✨' }] },
  { id: 'booking', question: { fr: 'Avez-vous besoin de réservation en ligne ?', en: 'Do you need online booking?', es: '¿Necesita reservas en línea?' }, options: [{ value: 'yes', label: { fr: 'Oui, essentiel', en: 'Yes, essential', es: 'Sí, esencial' }, icon: '✅' }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, icon: '❌' }] },
  { id: 'payments', question: { fr: 'Souhaitez-vous accepter les paiements en ligne ?', en: 'Do you want to accept online payments?', es: '¿Desea aceptar pagos en línea?' }, options: [{ value: 'yes', label: { fr: 'Oui', en: 'Yes', es: 'Sí' }, icon: '💳' }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, icon: '🚫' }] },
]

export const resources: Resource[] = [
  { id: 'r1', title: { fr: 'Guide SEO pour entrepreneurs', en: 'SEO Guide for entrepreneurs', es: 'Guía SEO para emprendedores' }, description: { fr: 'Les bases du référencement pour attirer plus de clients.', en: 'SEO basics to attract more clients.', es: 'Conceptos básicos de SEO para atraer más clientes.' }, type: 'pdf', downloadUrl: '/resources/guide-seo.pdf', image: '/images/resources/1.jpg' },
  { id: 'r2', title: { fr: 'Checklist de lancement', en: 'Launch checklist', es: 'Lista de verificación de lanzamiento' }, description: { fr: 'Tout vérifier avant de lancer votre site.', en: 'Everything to check before launching.', es: 'Todo lo que debe verificar antes de lanzar.' }, type: 'template', downloadUrl: '/resources/checklist.pdf', image: '/images/resources/2.jpg' },
  { id: 'r3', title: { fr: 'Template de contenu pour site web', en: 'Website content template', es: 'Plantilla de contenido para sitio web' }, description: { fr: 'Préparez facilement le contenu de votre futur site.', en: 'Easily prepare content for your future site.', es: 'Prepare fácilmente el contenido de su futuro sitio.' }, type: 'template', downloadUrl: '/resources/content-template.pdf', image: '/images/resources/3.jpg' },
]

export const beforeAfterExamples: BeforeAfterExample[] = [
  { id: 'ba1', title: { fr: 'Restaurant Le Gourmet', en: 'Le Gourmet Restaurant', es: 'Restaurante Le Gourmet' }, profession: 'restaurant', before: { image: '/images/ba/before-1.jpg', issues: { fr: ['Design daté', 'Pas de réservation en ligne', 'Non optimisé mobile'], en: ['Dated design', 'No online booking', 'Not mobile optimized'], es: ['Diseño anticuado', 'Sin reservas en línea', 'No optimizado móvil'] } }, after: { image: '/images/ba/after-1.jpg', improvements: { fr: ['Design moderne et appétissant', 'Réservation en ligne 24/7', 'Top 3 Google local'], en: ['Modern appetizing design', '24/7 online booking', 'Top 3 local Google'], es: ['Diseño moderno y apetitoso', 'Reservas en línea 24/7', 'Top 3 Google local'] } }, metrics: [{ label: { fr: 'Augmentation des réservations', en: 'Booking increase', es: 'Aumento de reservas' }, value: '+180%' }, { label: { fr: 'Temps gagné/semaine', en: 'Time saved/week', es: 'Tiempo ahorrado/semana' }, value: '8h' }] },
  { id: 'ba2', title: { fr: 'Cabinet Conseil Excellence', en: 'Excellence Consulting', es: 'Consultoría Excellence' }, profession: 'consultant', before: { image: '/images/ba/before-2.jpg', issues: { fr: ['Aucune présence web', 'Dépendance aux recommandations'], en: ['No web presence', 'Relying on referrals'], es: ['Sin presencia web', 'Dependencia de recomendaciones'] } }, after: { image: '/images/ba/after-2.jpg', improvements: { fr: ['Site professionnel premium', 'Google Business optimisé', 'Génération de leads automatique'], en: ['Premium professional website', 'Optimized Google Business', 'Automatic lead generation'], es: ['Sitio profesional premium', 'Google Business optimizado', 'Generación de leads automática'] } }, metrics: [{ label: { fr: 'Nouveaux clients/mois', en: 'New clients/month', es: 'Nuevos clientes/mes' }, value: '+15' }] },
  { id: 'ba3', title: { fr: 'Boutique Mode Élégance', en: 'Elegance Fashion Boutique', es: 'Boutique Moda Elegancia' }, profession: 'boutique', before: { image: '/images/ba/before-3.jpg', issues: { fr: ['Ventes uniquement en magasin', 'Pas de catalogue en ligne'], en: ['Store-only sales', 'No online catalog'], es: ['Ventas solo en tienda', 'Sin catálogo en línea'] } }, after: { image: '/images/ba/after-3.jpg', improvements: { fr: ['E-commerce complet', 'Paiements sécurisés', 'Catalogue produits attractif'], en: ['Complete e-commerce', 'Secure payments', 'Attractive product catalog'], es: ['E-commerce completo', 'Pagos seguros', 'Catálogo de productos atractivo'] } }, metrics: [{ label: { fr: 'Ventes en ligne/mois', en: 'Online sales/month', es: 'Ventas en línea/mes' }, value: '+45%' }] },
]
