import type { Plan, PortfolioItem, Testimonial, BlogPost, FAQItem, DiagnosticQuestion, OnboardingStep, Resource, BeforeAfterExample } from './types'

export const config = {
  SITE_URL: 'https://mindzy.me',
  CONTACT_EMAIL: 'contact@mindzy.me',
  CALENDLY_URL: 'https://calendly.com/mindzy/consultation',
  CONTRACT_URL: '/contract',
  WHATSAPP_PHONE_NUMBER: '+41XXXXXXXXX',
  WHATSAPP_PHONE_ID: 'XXXXXXXXXX',
  WHATSAPP_BUSINESS_ID: 'XXXXXXXXXX',
  WHATSAPP_API_VERSION: 'v18.0',
  WHATSAPP_LINK: 'https://wa.me/41XXXXXXXXX',
  LINKEDIN_URL: 'https://linkedin.com/company/mindzy',
}

export const plans: Plan[] = [
  { id: 'basic', price: 49, setup: 300, pages: 1, articles: 0, booking: false, payments: false, products: 0, gmb: true },
  { id: 'pro', price: 99, setup: 300, pages: 5, articles: 15, booking: true, payments: false, products: 0, gmb: true },
  { id: 'business', price: 129, setup: 500, pages: 5, articles: 15, booking: true, payments: true, products: 0, gmb: true },
  { id: 'ecommerce', price: 149, setup: 500, pages: 5, articles: 0, booking: false, payments: true, products: 20, gmb: true },
]

export const professions = ['consultant', 'restaurant', 'artisan', 'coach', 'boutique', 'freelance'] as const

export const portfolioItems: PortfolioItem[] = Array.from({ length: 40 }, (_, i) => ({
  id: `portfolio-${i + 1}`,
  title: {
    fr: ['Agence Créative', 'Restaurant Le Gourmet', 'Cabinet Conseil', 'Studio Photo', 'Boutique Mode', 'Coach Business', 'Artisan Menuisier', 'Salon de Coiffure', 'Architecte d\'Intérieur', 'Avocat & Associés'][i % 10] + ` ${Math.floor(i / 10) + 1}`,
    en: ['Creative Agency', 'Le Gourmet Restaurant', 'Consulting Firm', 'Photo Studio', 'Fashion Boutique', 'Business Coach', 'Carpenter Craft', 'Hair Salon', 'Interior Architect', 'Law Firm'][i % 10] + ` ${Math.floor(i / 10) + 1}`,
    es: ['Agencia Creativa', 'Restaurante Gourmet', 'Consultora', 'Estudio Fotográfico', 'Boutique Moda', 'Coach Empresarial', 'Artesano Carpintero', 'Salón de Belleza', 'Arquitecto Interior', 'Bufete de Abogados'][i % 10] + ` ${Math.floor(i / 10) + 1}`
  },
  description: { fr: 'Site web professionnel avec réservation en ligne et SEO optimisé.', en: 'Professional website with online booking and optimized SEO.', es: 'Sitio web profesional con reservas en línea y SEO optimizado.' },
  category: (['therapist', 'clinic', 'coach', 'ecom'] as const)[i % 4],
  profession: professions[i % professions.length],
  image: `/images/portfolio/placeholder-${(i % 6) + 1}.jpg`,
  featured: i < 6,
}))

export const testimonials: Testimonial[] = [
  { id: 't1', name: 'Marie Dupont', profession: { fr: 'Consultante Marketing', en: 'Marketing Consultant', es: 'Consultora de Marketing' }, quote: { fr: 'Mindzy a transformé ma visibilité en ligne. Je reçois 3x plus de demandes clients.', en: 'Mindzy transformed my online visibility. I receive 3x more client requests.', es: 'Mindzy transformó mi visibilidad. Recibo 3 veces más solicitudes de clientes.' }, rating: 5 },
  { id: 't2', name: 'Jean-Pierre Martin', profession: { fr: 'Restaurateur', en: 'Restaurant Owner', es: 'Restaurador' }, quote: { fr: 'Le système de réservation a révolutionné mon restaurant. Fini les appels sans fin !', en: 'The booking system revolutionized my restaurant. No more endless phone calls!', es: 'El sistema de reservas revolucionó mi restaurante. ¡Se acabaron las llamadas interminables!' }, rating: 5 },
  { id: 't3', name: 'Sophie Bernard', profession: { fr: 'Coach Business', en: 'Business Coach', es: 'Coach Empresarial' }, quote: { fr: 'Un accompagnement professionnel de A à Z. Mon site génère maintenant des clients automatiquement.', en: 'Professional support from A to Z. My site now generates clients automatically.', es: 'Apoyo profesional de principio a fin. Mi sitio genera clientes automáticamente.' }, rating: 5 },
  { id: 't4', name: 'Lucas Petit', profession: { fr: 'Photographe', en: 'Photographer', es: 'Fotógrafo' }, quote: { fr: 'Mon portfolio en ligne attire des clients que je n\'aurais jamais atteint autrement.', en: 'My online portfolio attracts clients I would never have reached otherwise.', es: 'Mi portafolio en línea atrae clientes que nunca habría alcanzado de otra manera.' }, rating: 5 },
  { id: 't5', name: 'Émilie Roux', profession: { fr: 'Avocate', en: 'Lawyer', es: 'Abogada' }, quote: { fr: 'Un site professionnel qui reflète parfaitement l\'image de mon cabinet.', en: 'A professional site that perfectly reflects my firm\'s image.', es: 'Un sitio profesional que refleja perfectamente la imagen de mi despacho.' }, rating: 5 },
  { id: 't6', name: 'Thomas Moreau', profession: { fr: 'Artisan Menuisier', en: 'Carpenter Craftsman', es: 'Artesano Carpintero' }, quote: { fr: 'Grâce à Mindzy, j\'ai maintenant une vitrine en ligne digne de mon savoir-faire.', en: 'Thanks to Mindzy, I now have an online showcase worthy of my craftsmanship.', es: 'Gracias a Mindzy, ahora tengo un escaparate en línea digno de mi artesanía.' }, rating: 5 },
]

export const blogPosts: BlogPost[] = [
  { slug: 'pourquoi-site-web-professionnel', title: { fr: 'Pourquoi chaque entrepreneur a besoin d\'un site en 2025', en: 'Why every entrepreneur needs a website in 2025', es: 'Por qué cada emprendedor necesita un sitio en 2025' }, excerpt: { fr: 'Découvrez pourquoi une présence en ligne est indispensable pour votre activité.', en: 'Discover why an online presence is essential for your business.', es: 'Descubra por qué una presencia en línea es esencial para su negocio.' }, category: 'marketing', author: 'Mindzy', date: '2025-01-15', image: '/images/blog/1.jpg', readingTime: 5 },
  { slug: 'seo-entrepreneurs-guide', title: { fr: 'SEO pour entrepreneurs : le guide complet', en: 'SEO for entrepreneurs: the complete guide', es: 'SEO para emprendedores: la guía completa' }, excerpt: { fr: 'Apprenez à optimiser votre site pour Google et attirer plus de clients.', en: 'Learn to optimize your site for Google and attract more clients.', es: 'Aprenda a optimizar su sitio para Google y atraer más clientes.' }, category: 'seo', author: 'Mindzy', date: '2025-01-10', image: '/images/blog/2.jpg', readingTime: 8 },
  { slug: 'reservation-en-ligne-avantages', title: { fr: '5 avantages de la réservation en ligne', en: '5 benefits of online booking', es: '5 beneficios de las reservas en línea' }, excerpt: { fr: 'Comment la réservation en ligne transforme votre activité.', en: 'How online booking transforms your business.', es: 'Cómo las reservas en línea transforman tu negocio.' }, category: 'productivite', author: 'Mindzy', date: '2025-01-05', image: '/images/blog/3.jpg', readingTime: 4 },
  { slug: 'google-business-optimisation', title: { fr: 'Optimiser votre fiche Google Business', en: 'Optimize your Google Business Profile', es: 'Optimiza tu perfil de Google Business' }, excerpt: { fr: 'Les étapes pour maximiser votre visibilité locale.', en: 'Steps to maximize your local visibility.', es: 'Pasos para maximizar tu visibilidad local.' }, category: 'seo', author: 'Mindzy', date: '2024-12-28', image: '/images/blog/4.jpg', readingTime: 6 },
  { slug: 'reseaux-sociaux-professionnels', title: { fr: 'Réseaux sociaux : guide pour professionnels', en: 'Social media: guide for professionals', es: 'Redes sociales: guía para profesionales' }, excerpt: { fr: 'Comment utiliser Instagram et LinkedIn pour développer votre activité.', en: 'How to use Instagram and LinkedIn to grow your business.', es: 'Cómo usar Instagram y LinkedIn para hacer crecer tu negocio.' }, category: 'marketing', author: 'Mindzy', date: '2024-12-20', image: '/images/blog/5.jpg', readingTime: 7 },
  { slug: 'creer-site-web-budget', title: { fr: 'Créer un site web professionnel avec un petit budget', en: 'Create a professional website on a budget', es: 'Crea un sitio web profesional con poco presupuesto' }, excerpt: { fr: 'Les solutions pour avoir un site de qualité sans se ruiner.', en: 'Solutions for a quality site without breaking the bank.', es: 'Soluciones para un sitio de calidad sin arruinarse.' }, category: 'business', author: 'Mindzy', date: '2024-12-15', image: '/images/blog/6.jpg', readingTime: 6 },
]

export const faqItems: FAQItem[] = [
  // Général
  { id: 'f1', question: { fr: 'Combien de temps pour créer mon site ?', en: 'How long to create my website?', es: '¿Cuánto tiempo para crear mi sitio?' }, answer: { fr: 'En moyenne 2 à 3 semaines après validation de vos contenus. Pour les projets urgents, nous proposons une option accélérée en 5-7 jours ouvrés avec un supplément.', en: 'On average 2 to 3 weeks after validating your content. For urgent projects, we offer an accelerated option in 5-7 business days with a supplement.', es: 'En promedio 2 a 3 semanas después de validar su contenido. Para proyectos urgentes, ofrecemos una opción acelerada en 5-7 días hábiles con un suplemento.' }, category: 'general' },
  { id: 'f2', question: { fr: 'Dois-je fournir du contenu (textes, images) ?', en: 'Do I need to provide content (texts, images)?', es: '¿Debo proporcionar contenido (textos, imágenes)?' }, answer: { fr: 'Idéalement oui, mais nous pouvons vous accompagner dans la rédaction de vos textes et proposons une banque d\'images professionnelles si nécessaire. Nous offrons également un service de shooting photo pour les plans Business et E-commerce.', en: 'Ideally yes, but we can help you write your texts and offer a professional image library if needed. We also offer a photo shooting service for Business and E-commerce plans.', es: 'Idealmente sí, pero podemos ayudarle a redactar sus textos y ofrecemos una biblioteca de imágenes profesionales si es necesario. También ofrecemos un servicio de sesión fotográfica para los planes Business y E-commerce.' }, category: 'general' },
  { id: 'f3', question: { fr: 'Puis-je voir des exemples de sites que vous avez créés ?', en: 'Can I see examples of sites you\'ve created?', es: '¿Puedo ver ejemplos de sitios que han creado?' }, answer: { fr: 'Absolument ! Consultez notre portfolio avec plus de 40 réalisations dans divers secteurs : restaurants, consultants, artisans, boutiques et bien d\'autres.', en: 'Absolutely! Check out our portfolio with over 40 projects in various sectors: restaurants, consultants, craftsmen, shops and many more.', es: '¡Absolutamente! Consulte nuestro portfolio con más de 40 proyectos en diversos sectores: restaurantes, consultores, artesanos, tiendas y muchos más.' }, category: 'general' },
  { id: 'f4', question: { fr: 'Travaillez-vous avec tous les secteurs d\'activité ?', en: 'Do you work with all business sectors?', es: '¿Trabajan con todos los sectores de actividad?' }, answer: { fr: 'Oui, nous accompagnons tous les entrepreneurs et professionnels : consultants, artisans, restaurants, boutiques, freelances, professions libérales, coachs, et bien d\'autres. Notre expertise s\'adapte à votre métier.', en: 'Yes, we support all entrepreneurs and professionals: consultants, craftsmen, restaurants, shops, freelancers, liberal professions, coaches, and many more. Our expertise adapts to your profession.', es: 'Sí, apoyamos a todos los emprendedores y profesionales: consultores, artesanos, restaurantes, tiendas, freelancers, profesiones liberales, coaches y muchos más. Nuestra experiencia se adapta a su profesión.' }, category: 'general' },

  // Tarification
  { id: 'f5', question: { fr: 'Que comprend l\'abonnement mensuel ?', en: 'What is included in the monthly subscription?', es: '¿Qué incluye la suscripción mensual?' }, answer: { fr: 'L\'abonnement comprend : hébergement premium haute performance, certificat SSL, mises à jour de sécurité, sauvegardes automatiques quotidiennes, support technique prioritaire, et modifications mineures mensuelles (textes, images). Vous n\'avez rien d\'autre à payer.', en: 'The subscription includes: premium high-performance hosting, SSL certificate, security updates, daily automatic backups, priority technical support, and monthly minor modifications (texts, images). You have nothing else to pay.', es: 'La suscripción incluye: alojamiento premium de alto rendimiento, certificado SSL, actualizaciones de seguridad, copias de seguridad automáticas diarias, soporte técnico prioritario y modificaciones menores mensuales (textos, imágenes). No tiene nada más que pagar.' }, category: 'pricing' },
  { id: 'f6', question: { fr: 'Y a-t-il des frais cachés ?', en: 'Are there hidden fees?', es: '¿Hay costos ocultos?' }, answer: { fr: 'Non, jamais. Nos prix sont transparents et tout compris. Le prix affiché inclut la création, l\'hébergement et le support. Seules les fonctionnalités supplémentaires hors forfait (refonte majeure, nouvelles pages, fonctionnalités sur mesure) peuvent entraîner des frais additionnels, toujours devisés à l\'avance.', en: 'No, never. Our prices are transparent and all-inclusive. The displayed price includes creation, hosting and support. Only additional features outside the plan (major redesign, new pages, custom features) may incur additional fees, always quoted in advance.', es: 'No, nunca. Nuestros precios son transparentes y todo incluido. El precio mostrado incluye creación, alojamiento y soporte. Solo las funciones adicionales fuera del plan (rediseño mayor, nuevas páginas, funciones personalizadas) pueden generar cargos adicionales, siempre presupuestados por adelantado.' }, category: 'pricing' },
  { id: 'f7', question: { fr: 'Puis-je changer de formule en cours de route ?', en: 'Can I change my plan later?', es: '¿Puedo cambiar de plan más adelante?' }, answer: { fr: 'Oui, vous pouvez upgrader votre formule à tout moment. Le passage à un plan supérieur est immédiat. Vous ne payez que la différence au prorata.', en: 'Yes, you can upgrade your plan at any time. The switch to a higher plan is immediate. You only pay the difference prorated.', es: 'Sí, puede actualizar su plan en cualquier momento. El cambio a un plan superior es inmediato. Solo paga la diferencia prorrateada.' }, category: 'pricing' },
  { id: 'f8', question: { fr: 'Quels sont les modes de paiement acceptés ?', en: 'What payment methods are accepted?', es: '¿Qué métodos de pago se aceptan?' }, answer: { fr: 'Nous acceptons les cartes bancaires (Visa, Mastercard), les virements SEPA, PayPal et Stripe. Le paiement est mensuel par prélèvement automatique, ou annuel avec 2 mois offerts.', en: 'We accept bank cards (Visa, Mastercard), SEPA transfers, PayPal and Stripe. Payment is monthly by automatic debit, or annual with 2 months free.', es: 'Aceptamos tarjetas bancarias (Visa, Mastercard), transferencias SEPA, PayPal y Stripe. El pago es mensual por débito automático, o anual con 2 meses gratis.' }, category: 'pricing' },
  { id: 'f9', question: { fr: 'Proposez-vous un paiement échelonné pour les frais de création ?', en: 'Do you offer installment payment for setup fees?', es: '¿Ofrecen pago a plazos para los costos de creación?' }, answer: { fr: 'Oui, nous proposons un paiement en 2 ou 3 fois sans frais pour les frais de mise en place. 50% à la commande, et le reste réparti sur les premiers mois.', en: 'Yes, we offer payment in 2 or 3 installments without fees for setup costs. 50% at order, and the rest spread over the first months.', es: 'Sí, ofrecemos pago en 2 o 3 cuotas sin cargos para los costos de instalación. 50% al pedido, y el resto repartido en los primeros meses.' }, category: 'pricing' },

  // Technique
  { id: 'f10', question: { fr: 'Mon site sera-t-il optimisé mobile ?', en: 'Will my site be mobile-optimized?', es: '¿Mi sitio estará optimizado para móvil?' }, answer: { fr: 'Oui, tous nos sites sont 100% responsive et optimisés pour mobile, tablette et desktop. Plus de 60% du trafic web vient du mobile, c\'est donc une priorité absolue dans notre conception.', en: 'Yes, all our sites are 100% responsive and optimized for mobile, tablet and desktop. Over 60% of web traffic comes from mobile, so it\'s an absolute priority in our design.', es: 'Sí, todos nuestros sitios son 100% responsivos y optimizados para móvil, tablet y escritorio. Más del 60% del tráfico web viene del móvil, por lo que es una prioridad absoluta en nuestro diseño.' }, category: 'technical' },
  { id: 'f11', question: { fr: 'Mon site sera-t-il bien référencé sur Google ?', en: 'Will my site rank well on Google?', es: '¿Mi sitio se posicionará bien en Google?' }, answer: { fr: 'Oui, tous nos sites sont construits avec les meilleures pratiques SEO : structure optimisée, balises méta, vitesse de chargement, données structurées, et optimisation Google Business. Nous fournissons également un rapport SEO mensuel.', en: 'Yes, all our sites are built with SEO best practices: optimized structure, meta tags, loading speed, structured data, and Google Business optimization. We also provide a monthly SEO report.', es: 'Sí, todos nuestros sitios están construidos con las mejores prácticas SEO: estructura optimizada, etiquetas meta, velocidad de carga, datos estructurados y optimización de Google Business. También proporcionamos un informe SEO mensual.' }, category: 'technical' },
  { id: 'f12', question: { fr: 'Puis-je avoir un nom de domaine personnalisé ?', en: 'Can I have a custom domain name?', es: '¿Puedo tener un nombre de dominio personalizado?' }, answer: { fr: 'Absolument ! Si vous avez déjà un domaine, nous le configurons gratuitement. Sinon, nous nous occupons de l\'achat et de la configuration (environ 15€/an selon l\'extension choisie).', en: 'Absolutely! If you already have a domain, we configure it for free. Otherwise, we handle the purchase and configuration (about €15/year depending on the extension chosen).', es: '¡Absolutamente! Si ya tiene un dominio, lo configuramos gratis. De lo contrario, nos encargamos de la compra y configuración (aproximadamente 15€/año según la extensión elegida).' }, category: 'technical' },
  { id: 'f13', question: { fr: 'Quelle est la vitesse de chargement de vos sites ?', en: 'What is the loading speed of your sites?', es: '¿Cuál es la velocidad de carga de sus sitios?' }, answer: { fr: 'Nos sites obtiennent généralement un score de 90+ sur Google PageSpeed. Nous utilisons les dernières technologies (Next.js, optimisation d\'images, CDN mondial) pour garantir des temps de chargement ultra-rapides.', en: 'Our sites typically score 90+ on Google PageSpeed. We use the latest technologies (Next.js, image optimization, global CDN) to ensure ultra-fast loading times.', es: 'Nuestros sitios generalmente obtienen una puntuación de 90+ en Google PageSpeed. Utilizamos las últimas tecnologías (Next.js, optimización de imágenes, CDN global) para garantizar tiempos de carga ultrarrápidos.' }, category: 'technical' },
  { id: 'f14', question: { fr: 'Mon site est-il sécurisé ?', en: 'Is my site secure?', es: '¿Mi sitio es seguro?' }, answer: { fr: 'Oui, la sécurité est notre priorité. Tous nos sites incluent : certificat SSL (HTTPS), protection contre les attaques DDoS, sauvegardes quotidiennes automatiques, et mises à jour de sécurité régulières.', en: 'Yes, security is our priority. All our sites include: SSL certificate (HTTPS), DDoS attack protection, automatic daily backups, and regular security updates.', es: 'Sí, la seguridad es nuestra prioridad. Todos nuestros sitios incluyen: certificado SSL (HTTPS), protección contra ataques DDoS, copias de seguridad automáticas diarias y actualizaciones de seguridad regulares.' }, category: 'technical' },

  // Support
  { id: 'f15', question: { fr: 'Proposez-vous un support technique ?', en: 'Do you offer technical support?', es: '¿Ofrecen soporte técnico?' }, answer: { fr: 'Oui, notre équipe support est disponible par email et WhatsApp du lundi au vendredi, 9h-18h. Temps de réponse moyen : moins de 4 heures. Pour les urgences, nous intervenons sous 2 heures.', en: 'Yes, our support team is available via email and WhatsApp Monday to Friday, 9am-6pm. Average response time: less than 4 hours. For emergencies, we intervene within 2 hours.', es: 'Sí, nuestro equipo de soporte está disponible por correo y WhatsApp de lunes a viernes, 9h-18h. Tiempo de respuesta promedio: menos de 4 horas. Para emergencias, intervenimos en menos de 2 horas.' }, category: 'support' },
  { id: 'f16', question: { fr: 'Puis-je modifier mon site moi-même ?', en: 'Can I modify my site myself?', es: '¿Puedo modificar mi sitio yo mismo?' }, answer: { fr: 'Pour les modifications simples (textes, images), vous pouvez nous les envoyer et nous les appliquons sous 24-48h. Pour ceux qui le souhaitent, nous proposons également une interface d\'administration simplifiée (en option).', en: 'For simple modifications (texts, images), you can send them to us and we apply them within 24-48h. For those who want it, we also offer a simplified admin interface (optional).', es: 'Para modificaciones simples (textos, imágenes), puede enviárnoslas y las aplicamos en 24-48h. Para quienes lo deseen, también ofrecemos una interfaz de administración simplificada (opcional).' }, category: 'support' },
  { id: 'f17', question: { fr: 'Que se passe-t-il si je veux arrêter ?', en: 'What happens if I want to stop?', es: '¿Qué pasa si quiero cancelar?' }, answer: { fr: 'Vous êtes libre d\'arrêter à tout moment, sans frais de résiliation. Nous vous fournissons une sauvegarde complète de votre site et pouvons vous aider à migrer vers un autre hébergeur si vous le souhaitez.', en: 'You are free to stop at any time, without termination fees. We provide you with a complete backup of your site and can help you migrate to another host if you wish.', es: 'Es libre de cancelar en cualquier momento, sin cargos de terminación. Le proporcionamos una copia de seguridad completa de su sitio y podemos ayudarle a migrar a otro hosting si lo desea.' }, category: 'support' },

  // Fonctionnalités
  { id: 'f18', question: { fr: 'Comment fonctionne le système de réservation en ligne ?', en: 'How does the online booking system work?', es: '¿Cómo funciona el sistema de reservas en línea?' }, answer: { fr: 'Notre système de réservation est intuitif : vos clients choisissent une date et un créneau disponible, reçoivent une confirmation automatique, et vous êtes notifié instantanément. Synchronisation avec Google Calendar incluse. Rappels automatiques par email/SMS.', en: 'Our booking system is intuitive: your clients choose an available date and slot, receive automatic confirmation, and you are instantly notified. Google Calendar sync included. Automatic email/SMS reminders.', es: 'Nuestro sistema de reservas es intuitivo: sus clientes eligen una fecha y horario disponible, reciben confirmación automática, y usted es notificado instantáneamente. Sincronización con Google Calendar incluida. Recordatorios automáticos por email/SMS.' }, category: 'features' },
  { id: 'f19', question: { fr: 'Puis-je vendre des produits ou services en ligne ?', en: 'Can I sell products or services online?', es: '¿Puedo vender productos o servicios en línea?' }, answer: { fr: 'Oui, avec nos plans Business et E-commerce. Nous intégrons des solutions de paiement sécurisées (Stripe, PayPal) et vous pouvez vendre des produits physiques, des services, des formations, ou des abonnements.', en: 'Yes, with our Business and E-commerce plans. We integrate secure payment solutions (Stripe, PayPal) and you can sell physical products, services, training, or subscriptions.', es: 'Sí, con nuestros planes Business y E-commerce. Integramos soluciones de pago seguras (Stripe, PayPal) y puede vender productos físicos, servicios, formaciones o suscripciones.' }, category: 'features' },
  { id: 'f20', question: { fr: 'Intégrez-vous les réseaux sociaux ?', en: 'Do you integrate social media?', es: '¿Integran las redes sociales?' }, answer: { fr: 'Oui, nous intégrons vos réseaux sociaux (Instagram, Facebook, LinkedIn, TikTok) directement sur votre site : flux Instagram, boutons de partage, liens vers vos profils, et widgets interactifs.', en: 'Yes, we integrate your social media (Instagram, Facebook, LinkedIn, TikTok) directly on your site: Instagram feed, share buttons, links to your profiles, and interactive widgets.', es: 'Sí, integramos sus redes sociales (Instagram, Facebook, LinkedIn, TikTok) directamente en su sitio: feed de Instagram, botones de compartir, enlaces a sus perfiles y widgets interactivos.' }, category: 'features' },
  { id: 'f21', question: { fr: 'Puis-je avoir un blog sur mon site ?', en: 'Can I have a blog on my site?', es: '¿Puedo tener un blog en mi sitio?' }, answer: { fr: 'Oui, nous incluons un blog optimisé SEO dans tous nos plans (sauf Basic). Vous pouvez nous envoyer vos articles et nous les publions, ou opter pour notre service de rédaction (articles optimisés SEO sur votre thématique).', en: 'Yes, we include an SEO-optimized blog in all our plans (except Basic). You can send us your articles and we publish them, or opt for our writing service (SEO-optimized articles on your topic).', es: 'Sí, incluimos un blog optimizado SEO en todos nuestros planes (excepto Basic). Puede enviarnos sus artículos y los publicamos, u optar por nuestro servicio de redacción (artículos optimizados SEO sobre su temática).' }, category: 'features' },
  { id: 'f22', question: { fr: 'Proposez-vous des formulaires de contact ?', en: 'Do you offer contact forms?', es: '¿Ofrecen formularios de contacto?' }, answer: { fr: 'Oui, chaque site inclut un formulaire de contact professionnel avec protection anti-spam. Vous recevez les messages directement par email et pouvez personnaliser les champs selon vos besoins.', en: 'Yes, each site includes a professional contact form with anti-spam protection. You receive messages directly by email and can customize fields according to your needs.', es: 'Sí, cada sitio incluye un formulario de contacto profesional con protección anti-spam. Recibe los mensajes directamente por correo y puede personalizar los campos según sus necesidades.' }, category: 'features' },
  { id: 'f23', question: { fr: 'Puis-je avoir plusieurs langues sur mon site ?', en: 'Can I have multiple languages on my site?', es: '¿Puedo tener varios idiomas en mi sitio?' }, answer: { fr: 'Oui, nous proposons des sites multilingues (français, anglais, espagnol, et autres sur demande). Chaque langue dispose de son propre contenu optimisé et d\'une URL dédiée pour le SEO.', en: 'Yes, we offer multilingual sites (French, English, Spanish, and others on request). Each language has its own optimized content and dedicated URL for SEO.', es: 'Sí, ofrecemos sitios multilingües (francés, inglés, español y otros bajo pedido). Cada idioma tiene su propio contenido optimizado y URL dedicada para SEO.' }, category: 'features' },

  // Processus
  { id: 'f24', question: { fr: 'Comment se déroule la création de mon site ?', en: 'How does the site creation process work?', es: '¿Cómo es el proceso de creación de mi sitio?' }, answer: { fr: '1. Appel découverte (30 min) pour comprendre vos besoins. 2. Proposition personnalisée sous 48h. 3. Création et première maquette sous 1 semaine. 4. Vos retours et ajustements. 5. Mise en ligne après validation. 6. Formation et support continu.', en: '1. Discovery call (30 min) to understand your needs. 2. Custom proposal within 48h. 3. Creation and first mockup within 1 week. 4. Your feedback and adjustments. 5. Launch after validation. 6. Training and ongoing support.', es: '1. Llamada de descubrimiento (30 min) para entender sus necesidades. 2. Propuesta personalizada en 48h. 3. Creación y primera maqueta en 1 semana. 4. Sus comentarios y ajustes. 5. Lanzamiento tras validación. 6. Formación y soporte continuo.' }, category: 'process' },
  { id: 'f25', question: { fr: 'Combien de modifications puis-je demander ?', en: 'How many modifications can I request?', es: '¿Cuántas modificaciones puedo solicitar?' }, answer: { fr: 'Pendant la création, vous avez droit à 2 rounds de révisions majeures inclus. Après le lancement, les modifications mineures (textes, images) sont illimitées et incluses dans votre abonnement. Les modifications structurelles sont devisées.', en: 'During creation, you are entitled to 2 rounds of major revisions included. After launch, minor modifications (texts, images) are unlimited and included in your subscription. Structural modifications are quoted.', es: 'Durante la creación, tiene derecho a 2 rondas de revisiones mayores incluidas. Después del lanzamiento, las modificaciones menores (textos, imágenes) son ilimitadas e incluidas en su suscripción. Las modificaciones estructurales se presupuestan.' }, category: 'process' },
]

export const diagnosticQuestions: DiagnosticQuestion[] = [
  { id: 'has-website', question: { fr: 'Avez-vous déjà un site web ?', en: 'Do you already have a website?', es: '¿Ya tiene un sitio web?' }, options: [{ value: 'yes', label: { fr: 'Oui', en: 'Yes', es: 'Sí' }, score: 2 }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, score: 0 }, { value: 'outdated', label: { fr: 'Oui, mais obsolète', en: 'Yes, but outdated', es: 'Sí, pero desactualizado' }, score: 1 }] },
  { id: 'has-booking', question: { fr: 'Avez-vous un système de réservation en ligne ?', en: 'Do you have online booking?', es: '¿Tiene reservas en línea?' }, options: [{ value: 'yes', label: { fr: 'Oui', en: 'Yes', es: 'Sí' }, score: 2 }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, score: 0 }, { value: 'basic', label: { fr: 'Basique', en: 'Basic', es: 'Básico' }, score: 1 }] },
  { id: 'has-gmb', question: { fr: 'Avez-vous une fiche Google Business ?', en: 'Do you have a Google Business profile?', es: '¿Tiene perfil de Google Business?' }, options: [{ value: 'yes-opt', label: { fr: 'Oui, optimisée', en: 'Yes, optimized', es: 'Sí, optimizado' }, score: 2 }, { value: 'yes-basic', label: { fr: 'Oui, pas optimisée', en: 'Yes, not optimized', es: 'Sí, no optimizado' }, score: 1 }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, score: 0 }] },
  { id: 'weekly-requests', question: { fr: 'Combien de demandes de RDV par semaine ?', en: 'How many appointment requests per week?', es: '¿Cuántas solicitudes de cita por semana?' }, options: [{ value: 'many', label: { fr: 'Plus de 10', en: 'More than 10', es: 'Más de 10' }, score: 2 }, { value: 'some', label: { fr: '5 à 10', en: '5 to 10', es: '5 a 10' }, score: 1 }, { value: 'few', label: { fr: 'Moins de 5', en: 'Less than 5', es: 'Menos de 5' }, score: 0 }] },
]

export const onboardingSteps: OnboardingStep[] = [
  { id: 'objective', question: { fr: 'Quel est votre objectif principal ?', en: 'What is your main objective?', es: '¿Cuál es su objetivo principal?' }, options: [{ value: 'visibility', label: { fr: 'Gagner en visibilité', en: 'Increase visibility', es: 'Aumentar visibilidad' }, icon: '👁️' }, { value: 'booking', label: { fr: 'Automatiser les réservations', en: 'Automate bookings', es: 'Automatizar reservas' }, icon: '📅' }, { value: 'sales', label: { fr: 'Vendre des produits/services', en: 'Sell products/services', es: 'Vender productos/servicios' }, icon: '💰' }, { value: 'credibility', label: { fr: 'Renforcer ma crédibilité', en: 'Strengthen credibility', es: 'Fortalecer credibilidad' }, icon: '🏆' }] },
  { id: 'assets', question: { fr: 'Quels éléments de marque avez-vous ?', en: 'What brand elements do you have?', es: '¿Qué elementos de marca tiene?' }, options: [{ value: 'logo', label: { fr: 'Logo professionnel', en: 'Professional logo', es: 'Logo profesional' }, icon: '🎨' }, { value: 'colors', label: { fr: 'Charte graphique', en: 'Brand guidelines', es: 'Guía de marca' }, icon: '🎯' }, { value: 'nothing', label: { fr: 'Rien pour l\'instant', en: 'Nothing yet', es: 'Nada por ahora' }, icon: '✨' }] },
  { id: 'booking', question: { fr: 'Avez-vous besoin de réservation en ligne ?', en: 'Do you need online booking?', es: '¿Necesita reservas en línea?' }, options: [{ value: 'yes', label: { fr: 'Oui, essentiel', en: 'Yes, essential', es: 'Sí, esencial' }, icon: '✅' }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, icon: '❌' }] },
  { id: 'payments', question: { fr: 'Souhaitez-vous accepter les paiements en ligne ?', en: 'Do you want to accept online payments?', es: '¿Desea aceptar pagos en línea?' }, options: [{ value: 'yes', label: { fr: 'Oui', en: 'Yes', es: 'Sí' }, icon: '💳' }, { value: 'no', label: { fr: 'Non', en: 'No', es: 'No' }, icon: '🚫' }] },
]

export const resources: Resource[] = [
  { id: 'r1', title: { fr: 'Guide SEO pour entrepreneurs', en: 'SEO Guide for entrepreneurs', es: 'Guía SEO para emprendedores' }, description: { fr: 'Les bases du référencement pour attirer plus de clients.', en: 'SEO basics to attract more clients.', es: 'Conceptos básicos de SEO para atraer más clientes.' }, type: 'pdf', downloadUrl: '/resources/guide-seo.pdf', image: '/images/resources/1.jpg' },
  { id: 'r2', title: { fr: 'Checklist de lancement', en: 'Launch checklist', es: 'Lista de verificación de lanzamiento' }, description: { fr: 'Tout vérifier avant de lancer votre site.', en: 'Everything to check before launching.', es: 'Todo lo que debe verificar antes de lanzar.' }, type: 'template', downloadUrl: '/resources/checklist.pdf', image: '/images/resources/2.jpg' },
  { id: 'r3', title: { fr: 'Template de contenu pour site web', en: 'Website content template', es: 'Plantilla de contenido para sitio web' }, description: { fr: 'Préparez facilement le contenu de votre futur site.', en: 'Easily prepare content for your future site.', es: 'Prepare fácilmente el contenido de su futuro sitio.' }, type: 'template', downloadUrl: '/resources/content-template.pdf', image: '/images/resources/3.jpg' },
]

export const beforeAfterExamples: BeforeAfterExample[] = [
  { id: 'ba1', title: { fr: 'Restaurant Le Gourmet', en: 'Le Gourmet Restaurant', es: 'Restaurante Le Gourmet' }, profession: 'restaurant', before: { image: '/images/ba/before-1.jpg', issues: { fr: ['Design daté', 'Pas de réservation en ligne', 'Non optimisé mobile'], en: ['Dated design', 'No online booking', 'Not mobile optimized'], es: ['Diseño anticuado', 'Sin reservas en línea', 'No optimizado móvil'] } }, after: { image: '/images/ba/after-1.jpg', improvements: { fr: ['Design moderne et appétissant', 'Réservation en ligne 24/7', 'Top 3 Google local'], en: ['Modern appetizing design', '24/7 online booking', 'Top 3 local Google'], es: ['Diseño moderno y apetitoso', 'Reservas en línea 24/7', 'Top 3 Google local'] } }, metrics: [{ label: { fr: 'Augmentation des réservations', en: 'Booking increase', es: 'Aumento de reservas' }, value: '+180%' }, { label: { fr: 'Temps gagné/semaine', en: 'Time saved/week', es: 'Tiempo ahorrado/semana' }, value: '8h' }] },
  { id: 'ba2', title: { fr: 'Cabinet Conseil Excellence', en: 'Excellence Consulting', es: 'Consultoría Excellence' }, profession: 'consultant', before: { image: '/images/ba/before-2.jpg', issues: { fr: ['Aucune présence web', 'Dépendance aux recommandations'], en: ['No web presence', 'Relying on referrals'], es: ['Sin presencia web', 'Dependencia de recomendaciones'] } }, after: { image: '/images/ba/after-2.jpg', improvements: { fr: ['Site professionnel premium', 'Google Business optimisé', 'Génération de leads automatique'], en: ['Premium professional website', 'Optimized Google Business', 'Automatic lead generation'], es: ['Sitio profesional premium', 'Google Business optimizado', 'Generación de leads automática'] } }, metrics: [{ label: { fr: 'Nouveaux clients/mois', en: 'New clients/month', es: 'Nuevos clientes/mes' }, value: '+15' }] },
  { id: 'ba3', title: { fr: 'Boutique Mode Élégance', en: 'Elegance Fashion Boutique', es: 'Boutique Moda Elegancia' }, profession: 'boutique', before: { image: '/images/ba/before-3.jpg', issues: { fr: ['Ventes uniquement en magasin', 'Pas de catalogue en ligne'], en: ['Store-only sales', 'No online catalog'], es: ['Ventas solo en tienda', 'Sin catálogo en línea'] } }, after: { image: '/images/ba/after-3.jpg', improvements: { fr: ['E-commerce complet', 'Paiements sécurisés', 'Catalogue produits attractif'], en: ['Complete e-commerce', 'Secure payments', 'Attractive product catalog'], es: ['E-commerce completo', 'Pagos seguros', 'Catálogo de productos atractivo'] } }, metrics: [{ label: { fr: 'Ventes en ligne/mois', en: 'Online sales/month', es: 'Ventas en línea/mes' }, value: '+45%' }] },
]
